// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdPathSegment } from "./CfdPathSegment";
import type { CfdValue } from "./CfdValue";
import type { RecordCoordinate } from "./RecordCoordinate";

export type BatchWriteFieldEditOutcome = { coordinate: RecordCoordinate, final_coordinate: RecordCoordinate, field_path: Array<CfdPathSegment>, old_value: CfdValue | null, new_value: CfdValue | null, };
