// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A schema-checked CFD function retained as executable source for runtimes.
 */
export type CfdFunction = { source: string, };
