// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CfdObject = { actual_type: string, fields: Record<string, import("./CfdValue").CfdValue>, };
