// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdDictKey } from "./CfdDictKey";
import type { CfdEnumValue } from "./CfdEnumValue";
import type { CfdRecord } from "./CfdRecord";

export type CfdValue = { "kind": "null" } | { "kind": "bool", "value": boolean } | { "kind": "int", "value": bigint } | { "kind": "float", "value": number } | { "kind": "string", "value": string } | { "kind": "enum", "value": CfdEnumValue } | { "kind": "object", "value": CfdRecord } | { "kind": "ref", "value": { target_type: string, target_key: string, } } | { "kind": "array", "value": Array<CfdValue> } | { "kind": "dict", "value": Array<[CfdDictKey, CfdValue]> };
