// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdDictKey } from "./CfdDictKey";
import type { CfdEnumValue } from "./CfdEnumValue";
import type { CfdFormattedString } from "./CfdFormattedString";
import type { CfdObject } from "./CfdObject";

export type CfdValue = { "kind": "option_none" } | { "kind": "option_some", "value": CfdValue } | { "kind": "result_ok", "value": CfdValue } | { "kind": "result_err", "value": CfdValue } | { "kind": "bool", "value": boolean } | { "kind": "int", "value": bigint } | { "kind": "float", "value": number } | { "kind": "string", "value": string } | { "kind": "formatted_string", "value": CfdFormattedString } | { "kind": "enum", "value": CfdEnumValue } | { "kind": "object", "value": CfdObject } | { "kind": "ref", "value": string } | { "kind": "array", "value": Array<CfdValue> } | { "kind": "dict", "value": Array<[CfdDictKey, CfdValue]> };
