// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdDictKey } from "./CfdDictKey";

export type CollectionEdit = { "kind": "array_append" } | { "kind": "array_remove", index: number, } | { "kind": "array_move", from: number, to: number, } | { "kind": "dict_insert", key: CfdDictKey, } | { "kind": "dict_remove", key: CfdDictKey, };
