// This file is generated by tauri-specta. Do not edit it manually.
import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core'

/** Commands */
export const commands = {
  buildProjectStatus: (sessionId: number) => __TAURI_INVOKE<boolean>(
    'plugin:typed-editor|build_project_status',
    { sessionId },
  ),
}
