// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdValue } from "./CfdValue";
import type { CreateFieldSource } from "./CreateFieldSource";
import type { CreateRequiredInput } from "./CreateRequiredInput";
import type { FieldAnnotation } from "./FieldAnnotation";

export type CreateRecordFieldDraft = { name: string, value: CfdValue | null, source: CreateFieldSource, required: CreateRequiredInput | null, annotation: FieldAnnotation | null, };
