// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateRequiredInput = { "kind": "ref", target_type: string, } | { "kind": "abstract_object", expected_type: string, concrete_types: Array<string>, } | { "kind": "recursive_object", type_name: string, } | { "kind": "unsupported", message: string, };
