// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdRecord } from "./CfdRecord";

export type DeletedRecordSnapshot = { record: CfdRecord, display_path: string, };
