// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeletedRecordSnapshot } from "./DeletedRecordSnapshot";
import type { FileRecords } from "./FileRecords";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type DeleteRecordOutcome = { file_records: FileRecords, diagnostics: Array<FlatDiagnostic>, 
/**
 * Authoritative snapshot of the deleted record so the front-end's undo
 * can re-insert it. `None` only when the record was missing before
 * deletion (defensive — should not happen in normal flows).
 */
deleted_snapshot: DeletedRecordSnapshot | null, };
