// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DimensionConfig = { variants: Array<string>, out_dir: string | null, 
/**
 * Human-readable label for this dimension. The editor falls back to a
 * built-in mapping (e.g. `"language" → "本地化"`) when missing, and to
 * the raw dimension name otherwise.
 */
display_name: string | null, };
