// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimensionFieldInfo } from "./DimensionFieldInfo";

export type DimensionInfo = { name: string, display_name: string, variants: Array<string>, out_dir: string | null, fields: Array<DimensionFieldInfo>, };
