// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DimensionFieldInfo = { source_type: string, source_field: string, synthesized_type: string, is_singleton: boolean, };
