// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimensionFieldInfo } from "./DimensionFieldInfo";

export type DimensionInfo = { 
/**
 * Stable dimension name from `coflow.yaml` (e.g. `"language"`).
 */
name: string, 
/**
 * Human-readable label resolved with the `display_name` fallback chain:
 * `config.display_name` → built-in (`"language" → "本地化"`) → `name`.
 */
display_name: string, variants: Array<string>, 
/**
 * Output directory (project-relative path string) for synthesized
 * dimension records, or `None` when no `out_dir` is configured.
 */
out_dir: string | null, 
/**
 * Schema fields belonging to this dimension. Wire only the source
 * type/field/synthesized type — the schema view itself is not part of
 * the editor's surface.
 */
fields: Array<DimensionFieldInfo>, };
