// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DimensionValueOrigin = { "kind": "file_span", path: string, start_line: number, start_character: number, end_line: number, end_character: number, } | { "kind": "table_cell", path: string, sheet: string | null, row: number, column: number, };
