// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";

export type EditorRecordGroup = { id: string, name: string, records: Array<RecordCoordinate>, };
