// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorProjectSettings = { table_column_widths: { [key in string]?: { [key in string]?: { [key in string]?: number } } }, };
