// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorErrorKind } from "./EditorErrorKind";
import type { FlatDiagnostic } from "./FlatDiagnostic";

/**
 * Structured error returned by `SessionStore` methods.
 *
 * Wire-shape: a discriminator (`kind`), a human-readable `message`, and an
 * optional list of structured `diagnostics` mirroring the same payload the
 * front-end already renders for build/load/check errors. The front-end can
 * route by `kind`, show `message` in a banner, and inject `diagnostics`
 * into the diagnostics panel without doing any string parsing.
 */
export type EditorError = { kind: EditorErrorKind, message: string, diagnostics: Array<FlatDiagnostic>, };
