// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorWorkspaceTab } from "./EditorWorkspaceTab";

export type EditorWorkspaceState = { tabs: Array<EditorWorkspaceTab>, active_tab_id: string | null };
