// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorRecordGroup } from "./EditorRecordGroup";
import type { ViewConfig } from "./ViewConfig";

export type EditorProjectSettings = { 
/**
 * Custom views keyed by (filePath, actualType). Default record/table
 * views are implicit and never stored here.
 */
views: { [key in string]?: { [key in string]?: Array<ViewConfig> } }, 
/**
 * Column widths for the implicit default table view, keyed by
 * (filePath, actualType, columnName). Custom table views carry their
 * own widths inside their [`ViewConfig`].
 */
default_table_column_widths: { [key in string]?: { [key in string]?: { [key in string]?: number } } }, record_groups: { [key in string]?: { [key in string]?: Array<EditorRecordGroup> } }, };
