// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpreadInfo } from "./SpreadInfo";

/**
 * Editor-only derived metadata for a single cell.
 *
 * - `spread_info`: cell came from a `...spread`; carries the source coordinate
 *   and a file-path hint for jump-to-source.
 * - `ref_target_file`: project-relative file path of the record this cell
 *   refers to. Only meaningful when `value` is a `CfdValue::Ref`.
 * - `enum_int_value`: integer backing the variant when `value` is a
 *   `CfdValue::Enum`. The variant name lives on the value itself; the
 *   integer is convenient for displays / filtering.
 * - `declared_type`: the schema type declared for this field, formatted for
 *   display and for collection element type derivation in the UI.
 * - `ref_target_type`: direct reference target type for scalar ref cells.
 * - `children`: nested annotations for object fields, array items, or dict
 *   values. Keys are field names, zero-based array indexes, or dict-key text.
 */
export type FieldAnnotation = { spread_info: SpreadInfo | null, ref_target_file: string | null, enum_int_value: bigint | null, declared_type: string | null, ref_target_type: string | null, children: { [key in string]?: FieldAnnotation }, };
