// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpreadInfo } from "./SpreadInfo";

/**
 * Editor-only derived metadata for a single cell.
 *
 * - `spread_info`: cell came from a `...spread`; carries the source coordinate
 *   and a file-path hint for jump-to-source.
 * - `ref_target_file`: project-relative file path of the record this cell
 *   refers to. Only meaningful when `value` is a `CfdValue::Ref`.
 * - `enum_int_value`: integer backing the variant when `value` is a
 *   `CfdValue::Enum`. The variant name lives on the value itself; the
 *   integer is convenient for displays / filtering.
 * - `declared_type`: the schema type declared for this field, formatted for
 *   display and for collection element type derivation in the UI.
 * - `ref_target_type`: direct reference target type for scalar ref cells.
 * - `enum_type`: the enum type name when this field's declared type resolves
 *   to an enum. Set regardless of value kind so the front-end can show an
 *   enum dropdown even for `null` cells.
 * - `nullable`: true when the declared type outer-wraps a `?`, so the UI
 *   can offer a "clear to null" option in dropdowns.
 * - `children`: nested annotations for object fields, array items, or dict
 *   values. Keys are field names, zero-based array indexes, or dict-key text.
 */
export type FieldAnnotation = { spread_info: SpreadInfo | null, ref_target_file: string | null, enum_int_value: bigint | null, declared_type: string | null, ref_target_type: string | null, enum_type: string | null, nullable: boolean, 
/**
 * True when this cell is exposed for inspection but cannot be edited.
 */
read_only: boolean, 
/**
 * Template annotation for elements of an array/dict field. Carries the
 * declared element type (and derived ref/enum/nullable metadata) so the
 * editor doesn't have to re-parse `declared_type` strings when adding a
 * new element or when the collection is empty. `None` for non-collection
 * fields.
 */
item_annotation: FieldAnnotation | null, 
/**
 * Concrete types that could occupy this field when the declared type is
 * an abstract object. Empty for non-polymorphic fields. The editor uses
 * this to expose a type-switch control on object cells and to prompt for
 * a concrete type when materializing a null polymorphic field.
 */
polymorphic_types: Array<string>,
/**
 * Concrete object type when schema context determines one.
 */
object_type: string | null,
/**
 * Direct object fields in inherited schema declaration order.
 */
field_order: Array<string>, children: { [key in string]?: FieldAnnotation }, };
