// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdValue } from "./CfdValue";
import type { FieldAnnotation } from "./FieldAnnotation";

/**
 * One cell in a record row.
 *
 * `value` is the authoritative `CfdValue`, shipped straight from the core
 * model. `annotation` carries spread, ref-target, and enum metadata.
 */
export type FieldCell = { name: string, value: CfdValue, annotation: FieldAnnotation | null, };
