// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldDiagnostic = { severity: string, field_path: string, message: string, };
