// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpreadInfo } from "./SpreadInfo";

/**
 * Editor-only derived metadata for a single cell.
 *
 * - `spread_info`: cell came from a `...spread`; carries the source coordinate
 *   and a file-path hint for jump-to-source.
 * - `ref_target_file`: project-relative file path of the record this cell
 *   refers to. Only meaningful when `value` is a `CfdValue::Ref`.
 * - `enum_int_value`: integer backing the variant when `value` is a
 *   `CfdValue::Enum`. The variant name lives on the value itself; the
 *   integer is convenient for displays / filtering.
 */
export type FieldAnnotation = { spread_info: SpreadInfo | null, ref_target_file: string | null, enum_int_value: bigint | null, };
