// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTypeOption = { name: string, display_name: string, record_count: number, is_singleton: boolean, };
