// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldMode } from "./FieldMode";
import type { RecordRow } from "./RecordRow";
import type { WriterCapabilities } from "./WriterCapabilities";

export type FileRecords = { file_path: string, type_names: Array<string>, records: Array<RecordRow>, field_modes: { [key in string]?: { [key in string]?: FieldMode } }, capabilities: WriterCapabilities, };
