// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordRow } from "./RecordRow";
import type { SourceCapabilities } from "./SourceCapabilities";

export type FileRecords = { file_path: string, type_names: Array<string>, records: Array<RecordRow>, 
/**
 * Per-source capabilities the front-end uses to grey out actions.
 * Bundles the writer's capabilities with its provider id so the UI can
 * also display "edited via excel" / "edited via lark-sheet".
 */
capabilities: SourceCapabilities, };
