// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTreeNode = { name: string, path: string, is_dir: boolean, in_sources: boolean, first_source_descendant: string | null, children: Array<FileTreeNode>, };
