// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticContext } from "./DiagnosticContext";
import type { DiagnosticTarget } from "./DiagnosticTarget";

/**
 * Wire-friendly flat view of a [`Diagnostic`].
 *
 * The target is authoritative: editor hosts execute it directly and never
 * infer navigation behavior from diagnostic codes or optional coordinates.
 */
export type FlatDiagnostic = { id: string, severity: string, code: string, stage: string, message: string, target: DiagnosticTarget, contexts: Array<DiagnosticContext>, };
