// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-friendly flat view of a [`Diagnostic`].
 *
 * Editor hosts use this as a single severity/code/message tuple anchored to
 * a file/record/field. Heavier-weight callers can keep the structured form.
 */
export type FlatDiagnostic = { severity: string, code: string, stage: string, message: string, file_path: string | null, actual_type: string | null, record_key: string | null, field_path: string | null, };
