// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginScope } from "./PluginScope";

export type FrontendPluginBundle = { manifest_path: string, id: string, name: string, description: string, version: string, source: string, scope: PluginScope, enabled: boolean, };
