// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphQuery = { file_path: string, depth: number | null, limit: number | null, };
