// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldMode } from "./FieldMode";
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

export type GraphData = { nodes: Array<GraphNode>, edges: Array<GraphEdge>, field_modes: { [key in string]?: { [key in string]?: FieldMode } }, };
