// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldCell } from "./FieldCell";
import type { RecordCoordinate } from "./RecordCoordinate";

export type GraphNode = { coordinate: RecordCoordinate, file_path: string, in_focus_file: boolean, is_collapsed: boolean, fields: Array<FieldCell>, };
