// Auto-generated by ts-rs — do not edit manually
// This is a placeholder; run cargo test export_all_bindings to regenerate

export type FieldValue =
  | { kind: "Null" }
  | { kind: "Bool"; v: boolean }
  | { kind: "Int"; v: number }
  | { kind: "Float"; v: number }
  | { kind: "Str"; v: string }
  | { kind: "Enum"; enum_name: string; variant: string; int_value: number }
  | { kind: "Object"; actual_type: string; fields: FieldCell[] }
  | { kind: "Ref"; target_type: string; target_key: string; target_file: string | null }
  | { kind: "Array"; items: FieldValue[] }
  | { kind: "Dict"; entries: DictEntry[] };

export type DictEntry = { key: DictKey; value: FieldValue };

export type DictKey =
  | { kind: "Str"; v: string }
  | { kind: "Int"; v: number }
  | { kind: "Enum"; enum_name: string; variant: string; int_value: number };

export type FieldPathSegment =
  | { kind: "Field"; name: string }
  | { kind: "Index"; i: number };

export type FieldCell = { name: string; value: FieldValue };

export type RecordRow = { key: string; actual_type: string; fields: FieldCell[]; spread_fields: string[] };

export type FileRecords = {
  file_path: string;
  type_names: string[];
  records: RecordRow[];
};

export type DiagnosticItem = {
  severity: string;
  code: string;
  stage: string;
  message: string;
  file_path: string | null;
  record_key: string | null;
  field_path: string | null;
};

export type FileTreeNode = {
  name: string;
  path: string;
  is_dir: boolean;
  in_sources: boolean;
  children: FileTreeNode[];
};

export type ProjectSnapshot = {
  session_id: number;
  file_tree: FileTreeNode[];
  diagnostics: DiagnosticItem[];
};

export type GraphNode = {
  id: string;
  key: string;
  actual_type: string;
  file_path: string;
  in_focus_file: boolean;
  is_collapsed: boolean;
  fields: FieldCell[];
};

export type GraphEdge = {
  source: string;
  target: string;
  field_path: string;
};

export type GraphData = { nodes: GraphNode[]; edges: GraphEdge[] };
