// Auto-generated by ts-rs — do not edit manually
// This is a placeholder; run cargo test export_all_bindings to regenerate

export type FieldValue =
  | { kind: "Null" }
  | { kind: "Bool"; v: boolean }
  | { kind: "Int"; v: number }
  | { kind: "Float"; v: number }
  | { kind: "Str"; v: string }
  | { kind: "Enum"; enum_name: string; variant: string; int_value: number }
  | { kind: "Object"; actual_type: string; fields: FieldCell[] }
  | { kind: "Ref"; target_type: string; target_key: string; target_file: string | null }
  | { kind: "Array"; items: FieldValue[] }
  | { kind: "Dict"; entries: DictEntry[] };

export type DictEntry = { key: DictKey; value: FieldValue };

export type DictKey =
  | { kind: "Str"; v: string }
  | { kind: "Int"; v: number }
  | { kind: "Enum"; enum_name: string; variant: string; int_value: number };

export type FieldPathSegment =
  | { kind: "Field"; name: string }
  | { kind: "Index"; i: number };

export type FieldCell = { name: string; value: FieldValue };

export type SpreadSource = { key: string; file: string };

export type RecordRow = { key: string; actual_type: string; fields: FieldCell[]; spread_fields: string[]; spread_sources: SpreadSource[]; is_fallback: boolean };

export type FileRecords = {
  file_path: string;
  type_names: string[];
  records: RecordRow[];
};

export type DiagnosticItem = {
  severity: string;
  code: string;
  stage: string;
  message: string;
  file_path: string | null;
  record_key: string | null;
  field_path: string | null;
};

export type FileTreeNode = {
  name: string;
  path: string;
  is_dir: boolean;
  in_sources: boolean;
  children: FileTreeNode[];
  record_count: number;
};

export type ProjectSnapshot = {
  session_id: number;
  file_tree: FileTreeNode[];
  diagnostics: DiagnosticItem[];
};

export type GraphNode = {
  id: string;
  key: string;
  actual_type: string;
  file_path: string;
  in_focus_file: boolean;
  is_collapsed: boolean;
  fields: FieldCell[];
};

export type GraphEdge = {
  source: string;
  target: string;
  field_path: string;
};

export type GraphData = { nodes: GraphNode[]; edges: GraphEdge[] };

export type RecordBrief = {
  key: string;
  actual_type: string;
  file_path: string;
  is_fallback: boolean;
};

export type FieldSchema = {
  name: string;
  type_str: string;
  /** If this field is `T?` where T is an Object type, this is T. */
  nullable_object_type: string | null;
  /** If this field is `[T?]` (Array of nullable Object T), this is T. */
  array_nullable_element_type: string | null;
  has_default: boolean;
  /** Human-readable default value string, or null if no default. */
  default_str: string | null;
};

export type SearchHit = {
  key: string;
  actual_type: string;
  file_path: string;
  /** The first field path that matched (e.g. "name" or "stats.hp") */
  match_field: string;
  /** The matched value as a short string for display */
  match_value: string;
};

export type IncomingRef = {
  /** The record key that holds the reference. */
  source_key: string;
  /** The type of the record that holds the reference. */
  source_type: string;
  /** File where the source record lives. */
  source_file: string;
  /** Field path within the source record where the Ref appears. */
  field_path: string;
};
