// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageRange } from "./LanguageRange";

export type LanguageDiagnostic = { range: LanguageRange, severity: number, message: string, code?: string, source?: string, };
