// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageTextEdit } from "./LanguageTextEdit";

export type LanguageCompletion = { label: string, detail?: string, kind?: number, insert_text?: string, insert_text_format?: number, documentation?: string, sort_text?: string, filter_text?: string, text_edit?: LanguageTextEdit, };
