// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSchemaField } from "./PluginSchemaField";

/**
 * Read-only schema information exposed to editor extensions.
 */
export type PluginSchemaType = { name: string, fields: Array<PluginSchemaField>, is_singleton: boolean, record_count: number, };
