// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One schema field in the extension-facing schema view.
 */
export type PluginSchemaField = { name: string, type_label: string, };
