// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectPluginDefaults = { views: { [key in string]?: string }, presentations: { [key in string]?: { [key in string]?: string } }, };
