// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDiffChange } from "./ProjectDiffChange";

export type ProjectFileDiff = { path: string, change: ProjectDiffChange, before?: string, after?: string,
/**
 * 仅包含统一 Diff 的 hunk；文件身份由 `path` 和 `change` 提供。
 */
patch: string, };
