// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDiffValue } from "./ProjectDiffValue";

export type ProjectRecordSnapshot = { file_path: string, values: Array<ProjectDiffValue>, };
