// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeNode } from "./FileTreeNode";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type ProjectSnapshot = { session_id: number, project_root: string, file_tree: Array<FileTreeNode>, diagnostics: Array<FlatDiagnostic>, };
