// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeNode } from "./FileTreeNode";
import type { FileTypeOption } from "./FileTypeOption";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type ProjectSnapshot = { session_id: number, revision: number, project_root: string, file_tree: Array<FileTreeNode>, file_types: { [key in string]?: Array<FileTypeOption> }, first_source_file: string | null, diagnostics: Array<FlatDiagnostic>, };
