// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDiffDiagnostic } from "./ProjectDiffDiagnostic";
import type { ProjectFileDiff } from "./ProjectFileDiff";
import type { ProjectRecordDiff } from "./ProjectRecordDiff";

export type ProjectDiff = { head_oid: string, target_revision: number, semantic_available: boolean, files: Array<ProjectFileDiff>, records: Array<ProjectRecordDiff>, diagnostics: Array<ProjectDiffDiagnostic>, };
