// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldCell } from "./FieldCell";
import type { RecordCoordinate } from "./RecordCoordinate";

/**
 * One top-level record's view inside a file.
 *
 * The record's stable identity is its `(actual_type, key)` coordinate.
 * `display_path` repeats the file path for hosts that already have a row.
 */
export type RecordRow = { coordinate: RecordCoordinate, display_path: string, fields: Array<FieldCell>, field_index: Record<string, number>, field_summaries: Record<string, string>, };
