// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, wire-friendly coordinate of a top-level record.
 *
 * Top-level records always have an `(actual_type, key)` pair that uniquely
 * identifies them inside a model build, even when synthetic dimension
 * records share keys with their source records.
 */
export type RecordCoordinate = { actual_type: string, key: string, };
