// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable business identity of a top-level record across model generations.
 *
 * [`CfdRecordId`] is only valid inside one model generation. Persisted and
 * wire-facing references to top-level records must use this coordinate.
 */
export type RecordCoordinate = { actual_type: string, key: string, };
