// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";

/**
 * Wire-friendly handle on a record the editor can jump to (a `Ref`'s
 * resolved target). Carries the coordinate + the file the record lives
 * in so the front-end can navigate without a follow-up query.
 */
export type RefTarget = { coordinate: RecordCoordinate, file_path: string, };
