// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlatDiagnostic } from "./FlatDiagnostic";
import type { RecordCoordinate } from "./RecordCoordinate";
import type { RecordRow } from "./RecordRow";

export type RenameRecordOutcome = { row: RecordRow, diagnostics: Array<FlatDiagnostic>, renamed: RecordCoordinate, };
