// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileRecords } from "./FileRecords";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type ReorderRecordsOutcome = { revision: number, file_records: FileRecords, diagnostics: Array<FlatDiagnostic>, affected_files: Array<string>, old_index: number | null, new_index: number | null, };
