// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-friendly view of a writer's capabilities + the provider id that
 * produced them. Replaces the previous standalone `SourceCapabilities`
 * struct.
 */
export type SourceCapabilities = { provider_id: string, can_edit_field: boolean, can_edit_key: boolean, can_insert_record: boolean, can_delete_record: boolean, 
/**
 * True when the host should treat a write as invalidating the whole
 * project view (force a full session rebuild) rather than relying on
 * a writer-supplied incremental outcome. Currently set by every writer
 * because the session always rebuilds — kept so the incremental-update
 * path can flip it per-writer later without breaking the wire shape.
 */
requires_full_refresh_after_write: boolean, is_remote: boolean, };
