// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";

/**
 * Source record coordinate of a spread-inherited cell, plus the field
 * path within the source record so the UI can render
 * `@Source.Key.path.to.field`.
 */
export type SpreadInfo = { source: RecordCoordinate, source_record_file: string | null, source_field_path: Array<string>, };
