// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewKind } from "./ViewKind";

/**
 * A user-created custom view over a (filePath, actualType).
 *
 * Table views use `columns` (ordered) + `column_widths`; graph views use
 * `relations` + `fields`. `group_filter` is common to both (see design
 * doc §4). Unused fields for a given `kind` are cleared during sanitize.
 */
export type ViewConfig = { id: string, name: string, kind: ViewKind, group_filter: string | null, columns: Array<string>, column_widths: { [key in string]?: number }, relations: Array<string>, fields: Array<string>, };
