// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";

/**
 * Outcome of an engine write transaction. Surfaces both the rebuilt
 * diagnostics and the coordinates that changed so callers can refresh local
 * caches without re-querying the full project.
 *
 * `renamed` is `Some(old, new)` when the write modified a record's `id`
 * field: the engine treats this as a coordinate change so the editor can
 * update routes, undo stacks, and any other long-lived references that
 * previously pointed at `old`.
 */
export type WriteOutcome = { touched: Array<RecordCoordinate>, inserted: RecordCoordinate | null, deleted: RecordCoordinate | null, renamed: [RecordCoordinate, RecordCoordinate] | null, };
