// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editing capabilities exposed to the front-end so the UI can grey out
 * disabled actions per source.
 *
 * Lower-bounded by the writer's actual implementation; the front-end must
 * not assume a writer can do more than these flags claim.
 */
export type WriterCapabilities = { provider_id: string, can_edit_field: boolean, can_edit_key: boolean, can_insert_record: boolean, can_delete_record: boolean, requires_full_refresh_after_write: boolean, is_remote: boolean, };
