// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlatDiagnostic } from "./FlatDiagnostic";
import type { RecordCoordinate } from "./RecordCoordinate";
import type { RecordRow } from "./RecordRow";

export type WriteFieldOutcome = { row: RecordRow, diagnostics: Array<FlatDiagnostic>, 
/**
 * `Some(new_coordinate)` when the write changed the host record's `id`
 * field. The front-end refreshes any caches keyed by the old coordinate.
 */
renamed: RecordCoordinate | null, };
