// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";

/**
 * Outcome of one staged write operation inside a mutation transaction.
 *
 * Provider diagnostics stay attached to the operation that emitted them.
 * Generation diagnostics are reported once by [`crate::MutationReport`].
 *
 * `renamed` is `Some(old, new)` when the write modified a record's `id`
 * field: the engine treats this as a coordinate change so the editor can
 * update routes, undo stacks, and any other long-lived references that
 * previously pointed at `old`.
 */
export type WriteOutcome = { touched: Array<RecordCoordinate>, inserted: RecordCoordinate | null, deleted: RecordCoordinate | null, renamed: [RecordCoordinate, RecordCoordinate] | null, reordered: boolean,
/**
 * Project-facing source paths actually changed by this operation.
 */
affected_files: Array<string>, };
