<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>Coflow</RootNamespace>
    <AssemblyName>Coflow.Runtime</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>9.0</LangVersion>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Coflow.Runtime</PackageId>
    <Description>Unity 2022+ and IL2CPP bindings for the Coflow Rust runtime.</Description>
    <PackageVersion>0.11.0</PackageVersion>
  </PropertyGroup>
</Project>
