use crate::contract::{Contract, FieldLabel, Message, ProtoField};
use std::fmt::Write;

pub(crate) fn render_contract(contract: &Contract) -> String {
    let mut out = String::from(
        "// Generated by Coflow. Data and contract must be deployed together.\nsyntax = \"proto3\";\n\npackage coflow.generated;\n\n",
    );
    for helper in &contract.helpers {
        render_message(&mut out, helper);
    }
    for record in &contract.records {
        let _ = writeln!(out, "message {} {{", record.message_name);
        if record.has_id {
            out.push_str("  string id = 1;\n  reserved 2 to 15;\n");
        }
        for field in &record.fields {
            render_field(&mut out, &field.proto, "  ");
        }
        out.push_str("}\n\n");
        if record.has_table {
            let _ = writeln!(out, "message {} {{", record.table_name);
            let _ = writeln!(out, "  repeated {} records = 1;", record.message_name);
            out.push_str("}\n\n");
        }
    }
    out
}

fn render_message(out: &mut String, message: &Message) {
    let _ = writeln!(out, "message {} {{", message.name);
    if let Some(oneof) = &message.oneof_name {
        let _ = writeln!(out, "  oneof {oneof} {{");
        for field in &message.fields {
            render_field(out, field, "    ");
        }
        out.push_str("  }\n");
    } else {
        for field in &message.fields {
            render_field(out, field, "  ");
        }
    }
    out.push_str("}\n\n");
}

fn render_field(out: &mut String, field: &ProtoField, indent: &str) {
    let label = match field.label {
        FieldLabel::Singular => "",
        FieldLabel::Optional => "optional ",
        FieldLabel::Repeated => "repeated ",
    };
    let _ = writeln!(
        out,
        "{indent}{label}{} {} = {};",
        field.type_name, field.name, field.number
    );
}
