use crate::model::CsharpProject;
use crate::{CsharpCodegenError, GeneratedFile};
use std::path::PathBuf;
use tera::{Context, Tera};

const ENUM_TEMPLATE: &str = include_str!("../templates/enum.cs.tera");
const TYPE_TEMPLATE: &str = include_str!("../templates/type.cs.tera");
const DATABASE_TEMPLATE: &str = include_str!("../templates/database.cs.tera");
const DATABASE_COMMON_MEMBERS_TEMPLATE: &str =
    include_str!("../templates/database_common_members.cs.tera");
const LOCALIZED_TEMPLATE: &str = include_str!("../templates/localized.cs.tera");

pub fn render_common_project(
    project: &CsharpProject,
) -> Result<Vec<GeneratedFile>, CsharpCodegenError> {
    let tera = templates()?;
    let mut files = Vec::new();

    for schema_enum in &project.enums {
        let mut context = Context::new();
        context.insert("namespace", &project.namespace);
        context.insert("enum", schema_enum);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(format!("{}.cs", schema_enum.name)),
            contents: render(&tera, "enum.cs.tera", &context)?,
        });
    }

    for schema_type in &project.types {
        let mut context = Context::new();
        context.insert("project", project);
        context.insert("type", schema_type);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(format!("{}.cs", schema_type.name)),
            contents: render(&tera, "type.cs.tera", &context)?,
        });
    }

    let mut database_context = Context::new();
    database_context.insert("project", project);
    files.push(GeneratedFile {
        relative_path: PathBuf::from(format!("{}.cs", project.database_class)),
        contents: render(&tera, "database.cs.tera", &database_context)?,
    });

    if project.uses_localization {
        let mut localized_context = Context::new();
        localized_context.insert("project", project);
        files.push(GeneratedFile {
            relative_path: PathBuf::from("Localized.cs"),
            contents: render(&tera, "localized.cs.tera", &localized_context)?,
        });
    }

    Ok(files)
}

/// Renders the schema-independent entry points used by the direct CFD
/// materializer. The generated code keeps source identity in a stable list
/// and delegates parsing/conversion to `Coflow.Cfd.Runtime`.
pub fn render_cfd_loader(project: &CsharpProject, sources: &[String]) -> String {
    let mut output = String::new();
    output.push_str("// <auto-generated />\n#nullable enable\nusing System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing Coflow.Cfd.Runtime;\n\n");
    output.push_str(&format!("namespace {}\n{{\n\n", project.namespace));
    output.push_str(&format!("public sealed partial class {}\n{{\n", project.database_class));
    output.push_str("    public static IReadOnlyList<string> SourceFiles { get; } = new[]\n    {\n");
    for source in sources {
        output.push_str(&format!("        \"{}\",\n", escape_csharp_string(source)));
    }
    output.push_str("    };\n\n");
    output.push_str("    private static IReadOnlyList<ICfdTypeBinding> Bindings { get; } = new ICfdTypeBinding[]\n    {\n");
    for schema_type in &project.types {
        output.push_str(&format!("        new {}CfdBinding(),\n", schema_type.name));
    }
    output.push_str("    };\n\n");
    for schema_type in &project.types {
        output.push_str(&format!(
            "    private sealed class {}CfdBinding : ICfdTypeBinding\n    {{\n        public string DeclaredType => \"{}\";\n        public object Read(CfdRecordNode record, CfdLoadContext context) => CfdMaterializer.Materialize<{}>(record, context);\n    }}\n\n",
            schema_type.name,
            escape_csharp_string(&schema_type.source_name),
            schema_type.name
        ));
    }
    output.push_str("    public static ");
    output.push_str(&project.database_class);
    output.push_str(" Load(Func<string, string?> loadText, CfdLoadOptions? options = null) => Load(new DelegateCfdSourceProvider(loadText), options);\n\n");
    output.push_str("    public static ");
    output.push_str(&project.database_class);
    output.push_str(" Load(ICfdSourceProvider provider, CfdLoadOptions? options = null) => LoadDocuments(CfdLoader.LoadDocuments(provider, SourceFiles, options), options);\n\n");
    output.push_str("    public static ");
    output.push_str(&project.database_class);
    output.push_str(" Load(IEnumerable<CfdSource> sources, CfdLoadOptions? options = null) => LoadDocuments(CfdParser.ParseAll(sources, options), options);\n\n");
    output.push_str("    private static ");
    output.push_str(&project.database_class);
    output.push_str(" LoadDocuments(IReadOnlyList<CfdDocument> documents, CfdLoadOptions? options)\n    {\n        var context = new CfdLoadContext(documents, options, Bindings);\n");
    for table in &project.database.tables {
        output.push_str(&format!(
            "        var {}Records = documents.SelectMany(document => document.Records).Where(record => record.DeclaredType == \"{}\").Select(record => CfdMaterializer.Materialize<{}>(record, context)).ToList();\n        var {}Index = {}Records.ToDictionary(record => record.{});\n        var {} = new Table<{}, {}>({}Records, {}Index);\n",
            table.records_var, escape_csharp_string(&table.source_name), table.name,
            table.index_var, table.records_var, table.id_property, table.accessor_parameter,
            table.id_type, table.name, table.records_var, table.index_var));
    }
    for singleton in &project.singletons {
        output.push_str(&format!(
            "        var {} = documents.SelectMany(document => document.Records).Where(record => record.DeclaredType == \"{}\").Select(record => CfdMaterializer.Materialize<{}>(record, context)).FirstOrDefault()!;\n",
            singleton.records_var, escape_csharp_string(&singleton.source_name), singleton.type_name));
    }
    output.push_str("        return new ");
    output.push_str(&project.database_class);
    output.push('(');
    let args = project
        .database
        .tables
        .iter()
        .map(|table| table.accessor_parameter.clone())
        .chain(project.singletons.iter().map(|singleton| singleton.records_var.clone()))
        .collect::<Vec<_>>();
    output.push_str(&args.join(", "));
    output.push_str(");\n    }\n}\n}\n");
    output
}

fn escape_csharp_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn templates() -> Result<Tera, CsharpCodegenError> {
    let mut tera = Tera::default();
    for (name, contents) in [
        ("enum.cs.tera", ENUM_TEMPLATE),
        ("type.cs.tera", TYPE_TEMPLATE),
        ("database.cs.tera", DATABASE_TEMPLATE),
        (
            "database_common_members.cs.tera",
            DATABASE_COMMON_MEMBERS_TEMPLATE,
        ),
        ("localized.cs.tera", LOCALIZED_TEMPLATE),
    ] {
        tera.add_raw_template(name, contents).map_err(|err| {
            CsharpCodegenError::new(format!("failed to add C# template `{name}`: {err}"))
        })?;
    }
    Ok(tera)
}

fn render(tera: &Tera, name: &str, context: &Context) -> Result<String, CsharpCodegenError> {
    tera.render(name, context)
        .map_err(|err| CsharpCodegenError::new(format!("failed to render `{name}`: {err}")))
}
