use crate::model::CsharpProject;
use crate::{CsharpCodegenError, GeneratedFile};
use coflow_language::CftSchema;
use coflow_runtime::codegen::{SourceManifestEntry, SourceOrigin};
use std::collections::BTreeMap;
use std::path::PathBuf;
use tera::{Context, Tera};

const ENUM_TEMPLATE: &str = include_str!("../templates/enum.cs.tera");
const TYPE_TEMPLATE: &str = include_str!("../templates/type.cs.tera");
const DATABASE_TEMPLATE: &str = include_str!("../templates/database.cs.tera");
const DATABASE_COMMON_MEMBERS_TEMPLATE: &str =
    include_str!("../templates/database_common_members.cs.tera");
const LOCALIZED_TEMPLATE: &str = include_str!("../templates/localized.cs.tera");

pub fn render_common_project(
    project: &CsharpProject,
) -> Result<Vec<GeneratedFile>, CsharpCodegenError> {
    let tera = templates()?;
    let mut files = Vec::new();

    for schema_enum in &project.enums {
        let mut context = Context::new();
        context.insert("namespace", &project.namespace);
        context.insert("enum", schema_enum);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(format!("{}.cs", schema_enum.name)),
            contents: render(&tera, "enum.cs.tera", &context)?,
        });
    }

    for schema_type in &project.types {
        let mut context = Context::new();
        context.insert("project", project);
        context.insert("type", schema_type);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(format!("{}.cs", schema_type.name)),
            contents: render(&tera, "type.cs.tera", &context)?,
        });
    }

    let mut database_context = Context::new();
    database_context.insert("project", project);
    files.push(GeneratedFile {
        relative_path: PathBuf::from(format!("{}.cs", project.database_class)),
        contents: render(&tera, "database.cs.tera", &database_context)?,
    });

    if project.uses_localization {
        let mut localized_context = Context::new();
        localized_context.insert("project", project);
        files.push(GeneratedFile {
            relative_path: PathBuf::from("Localized.cs"),
            contents: render(&tera, "localized.cs.tera", &localized_context)?,
        });
    }

    Ok(files)
}

/// Renders the schema-independent entry points used by the direct CFD
/// loader. The generated code keeps source identity in a stable list
/// and delegates parsing/conversion to `Coflow.Cfd.Runtime`.
pub fn render_cfd_loader(
    project: &CsharpProject,
    source_manifest: &[SourceManifestEntry],
    schema: &CftSchema,
) -> String {
    let sources = cfd_render_sources(source_manifest, schema);
    let mut output = String::new();
    output.push_str("// <auto-generated />\n#nullable enable\nusing System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing Coflow.Cfd.Runtime;\n\n");
    output.push_str(&format!("namespace {}\n{{\n\n", project.namespace));
    output.push_str(&format!(
        "public sealed partial class {}\n{{\n",
        project.database_class
    ));
    output.push_str(
        "    public static IReadOnlyList<string> SourceFiles { get; } = new string[]\n    {\n",
    );
    for source in &sources {
        output.push_str(&format!(
            "        \"{}\",\n",
            escape_csharp_string(&source.logical_path)
        ));
    }
    output.push_str("    };\n\n");
    output.push_str("    private static IReadOnlyList<ICfdTypeBinding> Bindings { get; } = new ICfdTypeBinding[]\n    {\n");
    for schema_type in project
        .types
        .iter()
        .filter(|schema_type| schema_type.loader_enabled)
    {
        output.push_str(&format!("        new {}CfdBinding(),\n", schema_type.name));
    }
    output.push_str("    };\n\n");
    for schema_type in project
        .types
        .iter()
        .filter(|schema_type| schema_type.loader_enabled)
    {
        let assignable_types = schema_type
            .loader_assignable_to
            .iter()
            .map(|name| format!("\"{}\"", escape_csharp_string(name)))
            .collect::<Vec<_>>()
            .join(", ");
        let object_fields = render_field_type_arms(schema_type, |field| field.object_type.as_deref());
        let reference_fields =
            render_field_type_arms(schema_type, |field| field.reference_type.as_deref());
        output.push_str(&format!(
            "    private sealed class {}CfdBinding : ICfdTypeBinding\n    {{\n        public string DeclaredType => \"{}\";\n        public IReadOnlyList<string> AssignableTypes {{ get; }} = new string[] {{ {} }};\n        public string? ObjectFieldType(string fieldName) => fieldName switch\n        {{\n{}\n            _ => null,\n        }};\n        public string? ReferenceFieldType(string fieldName) => fieldName switch\n        {{\n{}\n            _ => null,\n        }};\n        public object Read(CfdRecordNode record, CfdLoadContext context) => Read{}(record, context);\n    }}\n\n",
            schema_type.name,
            escape_csharp_string(&schema_type.source_name),
            assignable_types,
            object_fields,
            reference_fields,
            schema_type.name
        ));
    }
    render_enum_readers(&mut output, project);
    if project.uses_localization {
        render_localized_reader(&mut output);
    }
    for schema_type in project
        .types
        .iter()
        .filter(|schema_type| schema_type.loader_enabled)
    {
        render_type_reader(&mut output, schema_type);
    }
    for schema_type in project.types.iter().filter(|schema_type| {
        !schema_type.loader_enabled && !schema_type.loader_variants.is_empty()
    }) {
        render_polymorphic_reader(&mut output, schema_type);
    }
    output.push_str("    public static ");
    output.push_str(&project.database_class);
    output.push_str(" Load(Func<string, string?> loadText, CfdLoadOptions? options = null) => Load(new DelegateCfdTextLoader(loadText), options);\n\n");
    output.push_str("    public static ");
    output.push_str(&project.database_class);
    output.push_str(" Load(ICfdTextLoader loader, CfdLoadOptions? options = null) => LoadDocuments(NormalizeDocuments(CfdLoader.LoadDocuments(loader, SourceFiles, options)), options);\n\n");
    output.push_str("    public static ");
    output.push_str(&project.database_class);
    output.push_str(" Load(IEnumerable<CfdSource> sources, CfdLoadOptions? options = null) => LoadDocuments(NormalizeDocuments(CfdParser.ParseAll(sources, options)), options);\n\n");
    render_document_normalizer(&mut output, &sources);
    output.push_str("    private static ");
    output.push_str(&project.database_class);
    output.push_str(" LoadDocuments(IReadOnlyList<CfdDocument> documents, CfdLoadOptions? options)\n    {\n        var context = new CfdLoadContext(documents, options, Bindings);\n        var knownTypes = new HashSet<string>(Bindings.Select(binding => binding.DeclaredType), StringComparer.Ordinal);\n        var unsupported = documents.SelectMany(document => document.Records.Select(record => new { Document = document, Record = record })).FirstOrDefault(item => !knownTypes.Contains(item.Record.DeclaredType));\n        if (unsupported is not null)\n            throw new CfdLoadException(new[] { new CfdDiagnostic(\"CFD-REF-UNKNOWN-TYPE\", $\"CFD record `{unsupported.Record.Key}` uses unsupported type `{unsupported.Record.DeclaredType}`\", unsupported.Document.Path, unsupported.Record.Span) });\n        var singletonKeys = new HashSet<string>(StringComparer.Ordinal);\n");
    for table in &project.database.tables {
        output.push_str(&format!(
            "        var {}Records = documents.SelectMany(document => document.Records).Where(record => record.DeclaredType == \"{}\").Select(record => context.Resolve<{}>(\"{}\", record.Key)).ToList();\n        var {}Index = {}Records.ToDictionary(record => record.{});\n        var {} = new Table<{}, {}>({}Records, {}Index);\n",
            table.records_var, escape_csharp_string(&table.source_name), table.name, table.source_name,
            table.index_var, table.records_var, table.id_property, table.accessor_parameter,
            table.id_type, table.name, table.records_var, table.index_var));
    }
    for singleton in &project.singletons {
        let records = &singleton.records_var;
        let source = escape_csharp_string(&singleton.source_name);
        let type_name = &singleton.type_name;
        output.push_str(&format!(
            "        var {records}Matches = documents.SelectMany(document => document.Records.Select(record => new {{ Document = document, Record = record }})).Where(item => item.Record.DeclaredType == \"{source}\").ToList();\n        if ({records}Matches.Count != 1)\n            throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-SINGLETON-COUNT\", \"singleton `{source}` must have exactly one record\", {records}Matches.FirstOrDefault()?.Document.Path ?? string.Empty) }});\n        var {records}Match = {records}Matches[0];\n        if (!singletonKeys.Add({records}Match.Record.Key))\n            throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-SINGLETON-KEY-COLLISION\", $\"singleton record key `{{{records}Match.Record.Key}}` is used by more than one singleton type\", {records}Match.Document.Path, {records}Match.Record.Span) }});\n        var {records} = context.Resolve<{type_name}>(\"{source}\", {records}Match.Record.Key);\n"
        ));
    }
    output.push_str("        return new ");
    output.push_str(&project.database_class);
    output.push('(');
    let args = project
        .database
        .tables
        .iter()
        .map(|table| table.accessor_parameter.clone())
        .chain(
            project
                .singletons
                .iter()
                .map(|singleton| singleton.records_var.clone()),
        )
        .collect::<Vec<_>>();
    output.push_str(&args.join(", "));
    output.push_str(");\n    }\n}\n}\n");
    output
}

#[derive(Debug)]
struct CfdRenderSource {
    logical_path: String,
    dimensions: Vec<CfdDimensionMapping>,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct CfdDimensionMapping {
    source_type: String,
    field: String,
    generated_type: String,
    singleton: bool,
}

fn cfd_render_sources(
    manifest: &[SourceManifestEntry],
    schema: &CftSchema,
) -> Vec<CfdRenderSource> {
    let mut sources = BTreeMap::<String, Vec<CfdDimensionMapping>>::new();
    for source in manifest {
        let dimensions = sources.entry(source.logical_path.clone()).or_default();
        if let SourceOrigin::Dimension {
            source_type,
            field,
            ..
        } = &source.origin
        {
            let mapping = CfdDimensionMapping {
                source_type: source_type.clone(),
                field: field.clone(),
                generated_type: format!("{source_type}_{field}Variants"),
                singleton: schema
                    .resolve_type(source_type)
                    .is_some_and(|schema_type| schema_type.is_singleton),
            };
            if !dimensions.contains(&mapping) {
                dimensions.push(mapping);
                dimensions.sort();
            }
        }
    }
    sources
        .into_iter()
        .map(|(logical_path, dimensions)| CfdRenderSource {
            logical_path,
            dimensions,
        })
        .collect()
}

fn render_document_normalizer(output: &mut String, sources: &[CfdRenderSource]) {
    let dimension_sources = sources
        .iter()
        .filter(|source| !source.dimensions.is_empty())
        .collect::<Vec<_>>();
    if dimension_sources.is_empty() {
        output.push_str("    private static IReadOnlyList<CfdDocument> NormalizeDocuments(IReadOnlyList<CfdDocument> documents) => documents;\n\n");
        return;
    }

    output.push_str("    private static IReadOnlyList<CfdDocument> NormalizeDocuments(IReadOnlyList<CfdDocument> documents) => documents.Select(document => document.Path switch\n    {\n");
    for (index, source) in dimension_sources.iter().enumerate() {
        output.push_str(&format!(
            "        \"{}\" => NormalizeDimensionDocument{}(document),\n",
            escape_csharp_string(&source.logical_path),
            index
        ));
    }
    output.push_str("        _ => document,\n    }).ToList();\n\n");
    output.push_str("    private static CfdRecordNode NormalizeDimensionRecord(CfdRecordNode record, string sourceType, string generatedType, string path)\n    {\n        var validSourceType = Bindings.FirstOrDefault(binding => binding.DeclaredType == record.DeclaredType)?.AssignableTypes.Contains(sourceType, StringComparer.Ordinal) == true;\n        if (!validSourceType)\n            throw new CfdLoadException(new[] { new CfdDiagnostic(\"CFD-DIMENSION-TYPE\", $\"dimension record `{record.Key}` of type `{record.DeclaredType}` is not assignable to `{sourceType}`\", path, record.Span) });\n        return new CfdRecordNode(record.Key, generatedType, record.Fields, record.Span);\n    }\n\n");

    for (index, source) in dimension_sources.iter().enumerate() {
        output.push_str(&format!(
            "    private static CfdDocument NormalizeDimensionDocument{index}(CfdDocument document) => new CfdDocument(document.Path, document.Records.Select(record => "
        ));
        if source.dimensions.len() == 1 && !source.dimensions[0].singleton {
            let mapping = &source.dimensions[0];
            output.push_str(&format!(
                "NormalizeDimensionRecord(record, \"{}\", \"{}\", document.Path)",
                escape_csharp_string(&mapping.source_type),
                escape_csharp_string(&mapping.generated_type)
            ));
        } else {
            output.push_str("record.Key switch\n    {\n");
            for mapping in &source.dimensions {
                output.push_str(&format!(
                    "        \"{}\" => NormalizeDimensionRecord(record, \"{}\", \"{}\", document.Path),\n",
                    escape_csharp_string(&mapping.field),
                    escape_csharp_string(&mapping.source_type),
                    escape_csharp_string(&mapping.generated_type)
                ));
            }
            output.push_str("        _ => throw new CfdLoadException(new[] { new CfdDiagnostic(\"CFD-DIMENSION-FIELD\", $\"dimension record `{record.Key}` does not map to a generated field\", document.Path, record.Span) }),\n    }");
        }
        output.push_str(").ToList());\n\n");
    }
}

fn render_field_type_arms(
    schema_type: &crate::model::CsharpType,
    select: impl Fn(&crate::model::CsharpLoaderField) -> Option<&str>,
) -> String {
    schema_type
        .loader_fields
        .iter()
        .filter_map(|field| {
            select(field).map(|field_type| {
                format!(
                    "            \"{}\" => \"{}\",",
                    escape_csharp_string(&field.source_name),
                    escape_csharp_string(field_type)
                )
            })
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_enum_readers(output: &mut String, project: &CsharpProject) {
    for schema_enum in &project.enums {
        let enum_name = &schema_enum.name;
        let source_name = escape_csharp_string(&schema_enum.source_name);
        let arms = schema_enum
            .variants
            .iter()
            .map(|variant| {
                format!(
                    "            \"{}\" or \"{}.{}\" => ({}?){}.{},",
                    escape_csharp_string(&variant.source_name),
                    source_name,
                    escape_csharp_string(&variant.source_name),
                    enum_name,
                    enum_name,
                    variant.name
                )
            })
            .collect::<Vec<_>>();
        let text_arms = arms.join("\n");
        if schema_enum.is_flags {
            let mask = schema_enum
                .variants
                .iter()
                .fold(0_i64, |mask, variant| mask | variant.value);
            let flag_arms = schema_enum
                .variants
                .iter()
                .map(|variant| {
                    format!(
                        "            \"{}\" or \"{}.{}\" => (long?){}.{},",
                        escape_csharp_string(&variant.source_name),
                        source_name,
                        escape_csharp_string(&variant.source_name),
                        enum_name,
                        variant.name
                    )
                })
                .collect::<Vec<_>>();
            output.push_str(&format!(
                "    private static {enum_name} ReadEnum{enum_name}(CfdValueNode node) => CfdValueReader.Flags<{enum_name}>(node, \"{source_name}\", {mask}L, static token => token switch\n    {{\n{}\n            _ => null,\n    }});\n",
                flag_arms.join("\n")
            ));
        } else {
            output.push_str(&format!(
                "    private static {enum_name} ReadEnum{enum_name}(CfdValueNode node) => CfdValueReader.Enum<{enum_name}>(node, \"{source_name}\", static token => token switch\n    {{\n{}\n            _ => null,\n    }});\n",
                text_arms
            ));
        }
        output.push_str(&format!(
            "    private static {enum_name} ReadEnum{enum_name}Text(string value) => CfdValueReader.EnumText<{enum_name}>(value, \"{source_name}\", static token => token switch\n    {{\n{}\n            _ => null,\n    }});\n\n",
            text_arms
        ));
    }
}

fn render_localized_reader(output: &mut String) {
    output.push_str(
        "    private static Localized<T> ReadLocalized<T>(T defaultValue, CfdLoadContext context, string key, string variantsType, string recordKey, IReadOnlyList<string> variants, Func<CfdValueNode, CfdLoadContext, T> read)\n    {\n        var record = context.FindRecord(variantsType, recordKey);\n        if (record is null)\n            return new Localized<T>(key, defaultValue);\n        context.WithRecordPath(record, () => CfdValueReader.ValidateFields(record.Fields, new[] { \"default\" }.Concat(variants).ToArray()));\n        var values = new Dictionary<string, T>(StringComparer.Ordinal);\n        foreach (var variant in variants)\n        {\n            var node = CfdValueReader.FindField(record.Fields, variant);\n            if (node is not null && node is not CfdNullValue)\n                values.Add(variant, context.WithRecordPath(record, () => read(node, context)));\n        }\n        return new Localized<T>(key, defaultValue, values);\n    }\n\n",
    );
}

fn render_type_reader(output: &mut String, schema_type: &crate::model::CsharpType) {
    let field_args = schema_type
        .loader_id_type
        .as_ref()
        .map(|id_type| {
            if id_type == "string" {
                "key".to_string()
            } else {
                format!("ReadEnum{}Text(key)", id_type)
            }
        })
        .into_iter()
        .chain(schema_type.loader_fields.iter().map(|field| {
            let node = field.default_expression.as_ref().map_or_else(
                || {
                    format!(
                        "CfdValueReader.Field(fields, \"{}\")",
                        escape_csharp_string(&field.source_name)
                    )
                },
                |_| {
                    format!(
                        "CfdValueReader.FindField(fields, \"{}\")",
                        escape_csharp_string(&field.source_name)
                    )
                },
            );
            let expression = field
                .reader_expression
                .replace("VALUE", &node)
                .replace("CONTEXT", "context")
                .replace("RECORD_KEY", "key");
            field.default_expression.as_ref().map_or(expression.clone(), |default| {
                let value_name = format!("value{}", field.property_name);
                let value_expression = field
                    .reader_expression
                    .replace("VALUE", &value_name)
                    .replace("CONTEXT", "context")
                    .replace("RECORD_KEY", "key");
                format!(
                    "{node} is {{ }} {value_name} ? {value_expression} : {default}"
                )
            })
        }))
        .collect::<Vec<_>>();
    let expected_fields = schema_type
        .loader_fields
        .iter()
        .map(|field| format!("\"{}\"", escape_csharp_string(&field.source_name)))
        .collect::<Vec<_>>();
    let validation = if expected_fields.is_empty() {
        "CfdValueReader.ValidateFields(fields);".to_string()
    } else {
        format!(
            "CfdValueReader.ValidateFields(fields, {});",
            expected_fields.join(", ")
        )
    };
    output.push_str(&format!(
        "    private static {} Read{}(CfdRecordNode record, CfdLoadContext context)\n    {{\n        using var scope = context.EnterRecord(record.DeclaredType, record.Key);\n        return Read{}Fields(record.Fields, record.Key, context);\n    }}\n",
        schema_type.name,
        schema_type.name,
        schema_type.name
    ));
    if schema_type.loader_variants.is_empty() {
        output.push_str(&format!(
            "    private static {} Read{}(CfdValueNode node, CfdLoadContext context) => CfdValueReader.Object(node, context, \"{}\", Read{}Fields);\n",
            schema_type.name, schema_type.name, schema_type.source_name, schema_type.name
        ));
    } else {
        let arms = render_polymorphic_arms(schema_type);
        output.push_str(&format!(
            "    private static {} Read{}(CfdValueNode node, CfdLoadContext context)\n    {{\n        if (node is CfdDictionaryValue)\n            return CfdValueReader.Object(node, context, \"{}\", Read{}Fields);\n        if (node is not CfdObjectValue objectValue)\n            throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-VALUE-TYPE\", \"expected an object\", string.Empty, node.Span) }});\n        return objectValue.DeclaredType switch\n        {{\n            null or \"{}\" => CfdValueReader.Object(node, context, \"{}\", Read{}Fields),\n{}\n            _ => throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-REF-UNKNOWN-TYPE\", $\"unknown concrete type `{{objectValue.DeclaredType}}` for `{}`\", string.Empty, node.Span) }}),\n        }};\n    }}\n",
            schema_type.name,
            schema_type.name,
            schema_type.source_name,
            schema_type.name,
            schema_type.source_name,
            schema_type.source_name,
            schema_type.name,
            arms,
            schema_type.source_name
        ));
    }
    output.push_str(&format!(
        "    private static {} Read{}Fields(IReadOnlyList<CfdFieldNode> fields, string key, CfdLoadContext context)\n    {{\n        {}\n        return new {}({});\n    }}\n\n",
        schema_type.name,
        schema_type.name,
        validation,
        schema_type.name,
        field_args.join(", ")
    ));
}

fn render_polymorphic_reader(output: &mut String, schema_type: &crate::model::CsharpType) {
    let arms = render_polymorphic_arms(schema_type);
    output.push_str(&format!(
        "    private static {} Read{}(CfdValueNode node, CfdLoadContext context)\n    {{\n        if (node is not CfdObjectValue objectValue || objectValue.DeclaredType is null)\n            throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-VALUE-TYPE\", \"expected a concrete polymorphic object\", string.Empty, node.Span) }});\n        return objectValue.DeclaredType switch\n        {{\n{}\n            _ => throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-REF-UNKNOWN-TYPE\", $\"unknown concrete type `{{objectValue.DeclaredType}}` for `{}`\", string.Empty, node.Span) }}),\n        }};\n    }}\n\n",
        schema_type.name,
        schema_type.name,
        arms,
        schema_type.source_name
    ));
}

fn render_polymorphic_arms(schema_type: &crate::model::CsharpType) -> String {
    schema_type
        .loader_variants
        .iter()
        .map(|variant| {
            format!(
                "            \"{}\" => Read{}(node, context),",
                escape_csharp_string(&variant.source_name),
                variant.type_name
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn escape_csharp_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn templates() -> Result<Tera, CsharpCodegenError> {
    let mut tera = Tera::default();
    for (name, contents) in [
        ("enum.cs.tera", ENUM_TEMPLATE),
        ("type.cs.tera", TYPE_TEMPLATE),
        ("database.cs.tera", DATABASE_TEMPLATE),
        (
            "database_common_members.cs.tera",
            DATABASE_COMMON_MEMBERS_TEMPLATE,
        ),
        ("localized.cs.tera", LOCALIZED_TEMPLATE),
    ] {
        tera.add_raw_template(name, contents).map_err(|err| {
            CsharpCodegenError::new(format!("failed to add C# template `{name}`: {err}"))
        })?;
    }
    Ok(tera)
}

fn render(tera: &Tera, name: &str, context: &Context) -> Result<String, CsharpCodegenError> {
    tera.render(name, context)
        .map_err(|err| CsharpCodegenError::new(format!("failed to render `{name}`: {err}")))
}
