use crate::model::{CsharpAnnotation, CsharpProject};
use crate::{CsharpCodegenError, GeneratedFile};
use std::path::PathBuf;
use tera::{Context, Tera};

const ENUM_TEMPLATE: &str = include_str!("../templates/enum.cs.tera");
const TYPE_TEMPLATE: &str = include_str!("../templates/type.cs.tera");
const LOCALIZED_TEMPLATE: &str = include_str!("../templates/localized.cs.tera");

pub fn render_common_project(
    project: &CsharpProject,
) -> Result<Vec<GeneratedFile>, CsharpCodegenError> {
    let tera = templates()?;
    let mut files = Vec::new();

    for schema_enum in &project.enums {
        let mut context = Context::new();
        context.insert("namespace", &schema_enum.namespace);
        context.insert("enum", schema_enum);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(&schema_enum.relative_path),
            contents: render(&tera, "enum.cs.tera", &context)?,
        });
    }

    for schema_type in &project.types {
        let mut context = Context::new();
        context.insert("project", project);
        context.insert("type", schema_type);
        files.push(GeneratedFile {
            relative_path: PathBuf::from(&schema_type.relative_path),
            contents: render(&tera, "type.cs.tera", &context)?,
        });
    }

    if project.uses_localization {
        let mut localized_context = Context::new();
        localized_context.insert("project", project);
        files.push(GeneratedFile {
            relative_path: PathBuf::from("Localized.cs"),
            contents: render(&tera, "localized.cs.tera", &localized_context)?,
        });
    }

    Ok(files)
}

/// Renders the generated schema bridge consumed by the fixed C# Runtime.
/// The bridge is internal; CFT declarations remain the only public generated types.
pub fn render_cfd_metadata(project: &CsharpProject) -> String {
    let mut output = String::new();
    output.push_str("// <auto-generated />\n#nullable enable\nusing System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing System.Runtime.CompilerServices;\nusing CoflowRuntime;\n\n");
    output.push_str(&format!("namespace {}\n{{\n\n", project.namespace));
    output.push_str("internal sealed class CoflowGeneratedContract : ICoflowGeneratedContract\n{\n");
    output.push_str("    internal static readonly CoflowGeneratedContract Instance = new CoflowGeneratedContract();\n\n");
    output.push_str("    public IReadOnlyList<ICoflowTypeMetadata> Types { get; } = new ICoflowTypeMetadata[]\n    {\n");
    for schema_type in project
        .types
        .iter()
        .filter(|schema_type| schema_type.loader_enabled)
    {
        output.push_str(&format!("        new {}CoflowMetadata(),\n", schema_type.metadata_name));
    }
    output.push_str("    };\n\n");
    output.push_str("    public IReadOnlyList<ICoflowEnumMetadata> Enums { get; } = new ICoflowEnumMetadata[]\n    {\n");
    for schema_enum in &project.enums {
        output.push_str(&format!("        new {}CoflowEnumMetadata(),\n", schema_enum.metadata_name));
    }
    output.push_str("    };\n\n");
    output.push_str("    public IReadOnlyList<CoflowConstant> Constants { get; } = new CoflowConstant[]\n    {\n");
    for constant in &project.constants {
        let value = if constant.deferred {
            format!("static context => {}", constant.value_expression)
        } else {
            constant.value_expression.clone()
        };
        output.push_str(&format!(
            "        new CoflowConstant(\"{}\", typeof({}), {}),\n",
            escape_csharp_string(&constant.source_name),
            constant.runtime_type,
            value
        ));
    }
    output.push_str("    };\n\n");
    output.push_str("    [ModuleInitializer]\n    internal static void Register() => CoflowGeneratedRegistry.Register(Instance);\n\n");

    for schema_enum in &project.enums {
        let variants = schema_enum.variants.iter().map(|variant| format!(
            "            [\"{}\"] = {}.{},",
            escape_csharp_string(&variant.source_name), schema_enum.qualified_name, variant.name
        )).collect::<Vec<_>>().join("\n");
        let annotations = render_annotations(&schema_enum.annotations);
        let variant_annotations = schema_enum.variants.iter().map(|variant| format!(
            "            \"{}\" => {},",
            escape_csharp_string(&variant.source_name),
            render_annotations(&variant.annotations)
        )).collect::<Vec<_>>().join("\n");
        output.push_str(&format!(
            "    private sealed class {}CoflowEnumMetadata : ICoflowEnumMetadata\n    {{\n        public string DeclaredType => \"{}\";\n        public Type RuntimeType => typeof({});\n        public bool IsFlags => {};\n        public IReadOnlyList<CoflowAnnotation> Annotations {{ get; }} = {};\n        public IReadOnlyDictionary<string, object> Variants {{ get; }} = new Dictionary<string, object>(StringComparer.Ordinal)\n        {{\n{}\n        }};\n        public IReadOnlyList<CoflowAnnotation> VariantAnnotations(string variantName) => variantName switch\n        {{\n{}\n            _ => Array.Empty<CoflowAnnotation>(),\n        }};\n        public object FromInt64(long value) => ({})value;\n    }}\n\n",
            schema_enum.metadata_name,
            escape_csharp_string(&schema_enum.source_name),
            schema_enum.qualified_name,
            schema_enum.is_flags,
            annotations,
            variants,
            variant_annotations,
            schema_enum.qualified_name
        ));
    }

    for schema_type in project
        .types
        .iter()
        .filter(|schema_type| schema_type.loader_enabled)
    {
        let assignable_types = schema_type
            .loader_assignable_to
            .iter()
            .map(|name| format!("\"{}\"", escape_csharp_string(name)))
            .collect::<Vec<_>>()
            .join(", ");
        let object_fields = render_field_type_arms(schema_type, |field| field.object_type.as_deref());
        let reference_fields =
            render_field_type_arms(schema_type, |field| field.reference_type.as_deref());
        let singleton = project
            .singletons
            .iter()
            .any(|item| item.source_name == schema_type.source_name);
        let key_type = schema_type.loader_id_type.as_deref().unwrap_or("string");
        let parse_key = if key_type == "string" {
            "key".to_string()
        } else {
            let reader = project
                .enums
                .iter()
                .find(|schema_enum| schema_enum.qualified_name == key_type)
                .map_or_else(|| schema_type.metadata_name.as_str(), |schema_enum| {
                    schema_enum.metadata_name.as_str()
                });
            format!("ReadEnum{reader}Text(key)")
        };
        let get_key = if singleton {
            "string.Empty".to_string()
        } else {
            format!("(({})record).Id", schema_type.qualified_name)
        };
        let create_host = if schema_type.is_host {
            format!("CreateHost{}(context)", schema_type.metadata_name)
        } else {
            "throw new InvalidOperationException(\"The generated type is not @Host.\")".to_string()
        };
        let transfer_host = if schema_type.is_host {
            let copies = schema_type.host_fields.iter().map(|field| format!(
                "                (({})target).{} = (({})source).{};",
                schema_type.qualified_name,
                field.target,
                schema_type.qualified_name,
                field.target
            )).collect::<Vec<_>>().join("\n");
            let function_transfers = schema_type.functions.iter().map(|function| format!(
                "            new CoflowHostFunctionTransfer((({})source).{}, (({})target).{})",
                schema_type.qualified_name,
                function.slot_name,
                schema_type.qualified_name,
                function.slot_name
            )).collect::<Vec<_>>().join(",\n");
            let transfer_arguments = if function_transfers.is_empty() {
                String::new()
            } else {
                format!(",\n{function_transfers}")
            };
            format!(
                "(({})source)._coflowHost!.TransferStateTo((({})target)._coflowHost!, () =>\n        {{\n{}\n        }}{})",
                schema_type.qualified_name,
                schema_type.qualified_name,
                copies,
                transfer_arguments
            )
        } else {
            "throw new InvalidOperationException(\"The generated type is not @Host.\")".to_string()
        };
        let field_names = schema_type.loader_fields.iter()
            .map(|field| format!("\"{}\"", escape_csharp_string(&field.source_name)))
            .collect::<Vec<_>>().join(", ");
        let field_arms = schema_type.loader_fields.iter().map(|field| {
            let access = if field.is_function {
                schema_type.functions.iter()
                    .find(|function| function.source_name == field.source_name)
                    .map(|function| function.slot_name.as_str())
                    .unwrap_or_else(|| panic!("missing function model for {}", field.source_name))
            } else {
                field.property_name.as_str()
            };
            format!("            \"{}\" => (({})record).{},",
                escape_csharp_string(&field.source_name), schema_type.qualified_name, access)
        }).collect::<Vec<_>>().join("\n");
        let field_type_arms = schema_type.loader_fields.iter().map(|field| {
            let value_type = if field.is_function { "CoflowFunctionSlot" } else { &field.value_type };
            format!("            \"{}\" => typeof({}),",
                escape_csharp_string(&field.source_name), value_type)
        }).collect::<Vec<_>>().join("\n");
        let field_default_arms = schema_type.loader_fields.iter()
            .filter(|field| field.default_expression.is_some())
            .map(|field| format!(
                "            \"{}\" => true,",
                escape_csharp_string(&field.source_name)
            ))
            .collect::<Vec<_>>()
            .join("\n");
        let annotations = render_annotations(&schema_type.annotations);
        let field_annotation_arms = schema_type.loader_fields.iter().map(|field| format!(
            "            \"{}\" => {},",
            escape_csharp_string(&field.source_name),
            render_annotations(&field.annotations)
        )).collect::<Vec<_>>().join("\n");
        let metadata = format!(
            "    private sealed class {}CoflowMetadata : ICoflowTypeMetadata\n    {{\n        public Type RuntimeType => typeof({});\n        public Type KeyType => typeof({});\n        public bool IsSingleton => {};\n        public bool IsHost => false;\n        public string DeclaredType => \"{}\";\n        public IReadOnlyList<CoflowAnnotation> Annotations {{ get; }} = {};\n        public IReadOnlyList<string> AssignableTypes {{ get; }} = new string[] {{ {} }};\n        public IReadOnlyList<string> FieldNames {{ get; }} = new string[] {{ {} }};\n        public IReadOnlyList<CoflowAnnotation> FieldAnnotations(string fieldName) => fieldName switch\n        {{\n{}\n            _ => Array.Empty<CoflowAnnotation>(),\n        }};\n        public Type GetFieldType(string fieldName) => fieldName switch\n        {{\n{}\n            _ => throw new ArgumentException($\"unknown field `{{fieldName}}`\", nameof(fieldName)),\n        }};\n        public object GetField(object record, string fieldName) => fieldName switch\n        {{\n{}\n            _ => throw new ArgumentException($\"unknown field `{{fieldName}}`\", nameof(fieldName)),\n        }};\n        public bool HasFieldDefault(string fieldName) => fieldName switch\n        {{\n{}\n            _ => false,\n        }};\n        public object CreateObject(CfdLoadContext context, IReadOnlyDictionary<string, object?> fields) => CreateObject{}(context, fields);\n        public string? ObjectFieldType(string fieldName) => fieldName switch\n        {{\n{}\n            _ => null,\n        }};\n        public string? ReferenceFieldType(string fieldName) => fieldName switch\n        {{\n{}\n            _ => null,\n        }};\n        public object ParseKey(string key) => {};\n        public object GetKey(object record) => {};\n        public object Read(CfdRecordNode record, CfdLoadContext context) => Read{}(record, context);\n        public object CreateHost(CfdLoadContext context) => {};\n        public void TransferHostState(object source, object target) => {};\n    }}\n\n",
            schema_type.metadata_name,
            schema_type.qualified_name,
            key_type,
            singleton,
            escape_csharp_string(&schema_type.source_name),
            annotations,
            assignable_types,
            field_names,
            field_annotation_arms,
            field_type_arms,
            field_arms,
            field_default_arms,
            schema_type.metadata_name,
            object_fields,
            reference_fields,
            parse_key,
            get_key,
            schema_type.metadata_name,
            create_host
            ,transfer_host
        );
        output.push_str(&metadata.replace(
            "public bool IsHost => false;",
            &format!(
                "public bool IsHost => {};\n        public bool IsAbstract => {};\n        public bool IsSealed => {};\n        public bool IsRecord => {};",
                schema_type.is_host,
                schema_type.is_abstract,
                schema_type.is_sealed,
                schema_type.loader_id_type.is_some()
            ),
        ));
    }
    render_enum_readers(&mut output, project);
    if project.uses_localization {
        render_localized_reader(&mut output);
    }
    for schema_type in &project.types {
        render_object_factory(&mut output, schema_type);
    }
    for schema_type in project
        .types
        .iter()
        .filter(|schema_type| schema_type.loader_enabled)
    {
        if schema_type.is_host {
            render_host_reader(&mut output, schema_type);
        } else {
            render_type_reader(&mut output, schema_type);
        }
    }
    for schema_type in project.types.iter().filter(|schema_type| {
        !schema_type.loader_enabled && !schema_type.loader_variants.is_empty()
    }) {
        render_polymorphic_reader(&mut output, schema_type);
    }
    output.push_str("}\n}\n");
    output
}

fn render_object_factory(output: &mut String, schema_type: &crate::model::CsharpType) {
    if schema_type.is_abstract || schema_type.is_host {
        output.push_str(&format!(
            "    private static object CreateObject{}(CfdLoadContext context, IReadOnlyDictionary<string, object?> fields) => throw new InvalidOperationException(\"CFT type `{}` cannot be constructed as an object.\");\n\n",
            schema_type.metadata_name,
            escape_csharp_string(&schema_type.source_name),
        ));
        return;
    }

    let mut arguments = Vec::new();
    if schema_type.uses_host_slot {
        arguments.push("null".to_string());
    }
    if let Some(id_type) = &schema_type.loader_id_type {
        arguments.push(if id_type == "string" {
            "string.Empty".to_string()
        } else {
            format!("default({id_type})")
        });
    }
    arguments.extend(schema_type.loader_fields.iter().enumerate().map(|(index, field)| {
        if field.is_function {
            return "default!".to_string();
        }
        let supplied = format!(
            "fields.TryGetValue(\"{}\", out var value{index}) ? ({})value{index}!",
            escape_csharp_string(&field.source_name),
            field.value_type,
        );
        match &field.default_expression {
            Some(default) => format!("{supplied} : {default}"),
            None => format!(
                "{supplied} : throw new ArgumentException(\"missing object field `{}`\", nameof(fields))",
                escape_csharp_string(&field.source_name),
            ),
        }
    }));
    let key_declaration = schema_type
        .loader_fields
        .iter()
        .filter_map(|field| field.default_expression.as_deref())
        .any(|default| default.contains("key"))
        .then_some("        const string key = \"\";\n")
        .unwrap_or_default();
    output.push_str(&format!(
        "    private static object CreateObject{}(CfdLoadContext context, IReadOnlyDictionary<string, object?> fields)\n    {{\n{}        return new {}({});\n    }}\n\n",
        schema_type.metadata_name,
        key_declaration,
        schema_type.qualified_name,
        arguments.join(", "),
    ));
}

fn render_field_type_arms(
    schema_type: &crate::model::CsharpType,
    select: impl Fn(&crate::model::CsharpLoaderField) -> Option<&str>,
) -> String {
    schema_type
        .loader_fields
        .iter()
        .filter_map(|field| {
            select(field).map(|field_type| {
                format!(
                    "            \"{}\" => \"{}\",",
                    escape_csharp_string(&field.source_name),
                    escape_csharp_string(field_type)
                )
            })
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_enum_readers(output: &mut String, project: &CsharpProject) {
    for schema_enum in &project.enums {
        let enum_name = &schema_enum.qualified_name;
        let reader_name = &schema_enum.metadata_name;
        let source_name = escape_csharp_string(&schema_enum.source_name);
        let arms = schema_enum
            .variants
            .iter()
            .map(|variant| {
                format!(
                    "            \"{}\" or \"{}::{}\" => ({}?){}.{},",
                    escape_csharp_string(&variant.source_name),
                    source_name,
                    escape_csharp_string(&variant.source_name),
                    enum_name,
                    enum_name,
                    variant.name
                )
            })
            .collect::<Vec<_>>();
        let text_arms = arms.join("\n");
        if schema_enum.is_flags {
            let mask = schema_enum
                .variants
                .iter()
                .fold(0_i64, |mask, variant| mask | variant.value);
            let flag_arms = schema_enum
                .variants
                .iter()
                .map(|variant| {
                    format!(
                        "            \"{}\" or \"{}::{}\" => (long?){}.{},",
                        escape_csharp_string(&variant.source_name),
                        source_name,
                        escape_csharp_string(&variant.source_name),
                        enum_name,
                        variant.name
                    )
                })
                .collect::<Vec<_>>();
            output.push_str(&format!(
                "    private static {enum_name} ReadEnum{reader_name}(CfdValueNode node) => CfdValueReader.Flags<{enum_name}>(node, \"{source_name}\", {mask}L, static token => token switch\n    {{\n{}\n            _ => null,\n    }});\n",
                flag_arms.join("\n")
            ));
        } else {
            output.push_str(&format!(
                "    private static {enum_name} ReadEnum{reader_name}(CfdValueNode node) => CfdValueReader.Enum<{enum_name}>(node, \"{source_name}\", static token => token switch\n    {{\n{}\n            _ => null,\n    }});\n",
                text_arms
            ));
        }
        output.push_str(&format!(
            "    private static {enum_name} ReadEnum{reader_name}Text(string value) => CfdValueReader.EnumText<{enum_name}>(value, \"{source_name}\", static token => token switch\n    {{\n{}\n            _ => null,\n    }});\n\n",
            text_arms
        ));
    }
}

fn render_localized_reader(output: &mut String) {
    output.push_str(
        "    private static Localized<T> ReadLocalized<T>(T defaultValue, CfdLoadContext context, string key, string variantsType, string recordKey, IReadOnlyList<string> variants, Func<CfdValueNode, CfdLoadContext, T> read)\n    {\n        var record = context.FindRecord(variantsType, recordKey);\n        if (record is null)\n            return new Localized<T>(key, defaultValue);\n        context.WithRecordPath(record, () => CfdValueReader.ValidateFields(record.Fields, new[] { \"default\" }.Concat(variants).ToArray()));\n        var values = new Dictionary<string, T>(StringComparer.Ordinal);\n        foreach (var variant in variants)\n        {\n            var node = CfdValueReader.FindField(record.Fields, variant);\n            if (node is not null && node is not CfdNoneValue)\n                values.Add(variant, context.WithRecordPath(record, () => read(node, context)));\n        }\n        return new Localized<T>(key, defaultValue, values);\n    }\n\n",
    );
}

fn render_type_reader(output: &mut String, schema_type: &crate::model::CsharpType) {
    let field_args = schema_type
        .loader_id_type
        .as_ref()
        .map(|_| {
            schema_type.loader_id_reader.as_ref().map_or_else(
                || "key".to_string(),
                |reader| format!("ReadEnum{reader}Text(key)"),
            )
        })
        .into_iter()
        .chain(schema_type.loader_fields.iter().map(|field| {
            let node = if field.is_function {
                format!(
                    "CfdValueReader.FindField(fields, \"{}\")",
                    escape_csharp_string(&field.source_name)
                )
            } else {
                field.default_expression.as_ref().map_or_else(
                || {
                    format!(
                        "CfdValueReader.Field(fields, \"{}\")",
                        escape_csharp_string(&field.source_name)
                    )
                },
                |_| {
                    format!(
                        "CfdValueReader.FindField(fields, \"{}\")",
                        escape_csharp_string(&field.source_name)
                    )
                },
                )
            };
            let expression = field
                .reader_expression
                .replace("VALUE", &node)
                .replace("CONTEXT", "context")
                .replace("RECORD_KEY", "key");
            field.default_expression.as_ref().map_or(expression.clone(), |default| {
                let value_name = format!("value{}", field.property_name);
                let value_expression = field
                    .reader_expression
                    .replace("VALUE", &value_name)
                    .replace("CONTEXT", "context")
                    .replace("RECORD_KEY", "key");
                format!(
                    "{node} is {{ }} {value_name} ? {value_expression} : {default}"
                )
            })
        }))
        .collect::<Vec<_>>();
    let field_args = if schema_type.uses_host_slot {
        std::iter::once("null".to_string())
            .chain(field_args)
            .collect::<Vec<_>>()
    } else {
        field_args
    };
    let expected_fields = schema_type
        .loader_fields
        .iter()
        .map(|field| format!("\"{}\"", escape_csharp_string(&field.source_name)))
        .collect::<Vec<_>>();
    let validation = if expected_fields.is_empty() {
        "CfdValueReader.ValidateFields(fields);".to_string()
    } else {
        format!(
            "CfdValueReader.ValidateFields(fields, {});",
            expected_fields.join(", ")
        )
    };
    output.push_str(&format!(
        "    private static {} Read{}(CfdRecordNode record, CfdLoadContext context)\n    {{\n        using var scope = context.EnterRecord(record.DeclaredType, record.Key);\n        return Read{}Fields(record.Fields, record.Key, context);\n    }}\n",
        schema_type.qualified_name,
        schema_type.metadata_name,
        schema_type.metadata_name
    ));
    if schema_type.loader_variants.is_empty() {
        output.push_str(&format!(
            "    private static {} Read{}(CfdValueNode node, CfdLoadContext context) => CfdValueReader.Object(node, context, \"{}\", Read{}Fields);\n",
            schema_type.qualified_name,
            schema_type.metadata_name,
            schema_type.source_name,
            schema_type.metadata_name
        ));
    } else {
        let arms = render_polymorphic_arms(schema_type);
        output.push_str(&format!(
            "    private static {} Read{}(CfdValueNode node, CfdLoadContext context)\n    {{\n        if (node is CfdDictionaryValue)\n            return CfdValueReader.Object(node, context, \"{}\", Read{}Fields);\n        if (node is not CfdObjectValue objectValue)\n            throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-VALUE-TYPE\", \"expected an object\", string.Empty, node.Span) }});\n        return objectValue.DeclaredType switch\n        {{\n            null or \"{}\" => CfdValueReader.Object(node, context, \"{}\", Read{}Fields),\n{}\n            _ => throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-REF-UNKNOWN-TYPE\", $\"unknown concrete type `{{objectValue.DeclaredType}}` for `{}`\", string.Empty, node.Span) }}),\n        }};\n    }}\n",
            schema_type.qualified_name,
            schema_type.metadata_name,
            schema_type.source_name,
            schema_type.metadata_name,
            schema_type.source_name,
            schema_type.source_name,
            schema_type.metadata_name,
            arms,
            schema_type.source_name
        ));
    }
    output.push_str(&format!(
        "    private static {} Read{}Fields(IReadOnlyList<CfdFieldNode> fields, string key, CfdLoadContext context)\n    {{\n        {}\n        return new {}({});\n    }}\n\n",
        schema_type.qualified_name,
        schema_type.metadata_name,
        validation,
        schema_type.qualified_name,
        field_args.join(", ")
    ));
}

fn render_host_reader(output: &mut String, schema_type: &crate::model::CsharpType) {
    let function_args = schema_type
        .loader_fields
        .iter()
        .filter(|field| field.is_function)
        .map(|field| {
            field
                .reader_expression
                .replace("VALUE", "null")
                .replace("CONTEXT", "context")
                .replace("RECORD_KEY", "string.Empty")
        })
        .collect::<Vec<_>>();
    let constructor_args = std::iter::once("context.Host()".to_string())
        .chain(function_args)
        .collect::<Vec<_>>()
        .join(", ");
    output.push_str(&format!(
        "    private static {} Read{}(CfdRecordNode record, CfdLoadContext context) => throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-HOST-RECORD\", \"CFD cannot declare @Host type `{}`\", string.Empty, record.Span) }});\n    private static object CreateHost{}(CfdLoadContext context)\n    {{\n        using var scope = context.EnterRecord(\"{}\", string.Empty);\n        return new {}({});\n    }}\n\n",
        schema_type.qualified_name,
        schema_type.metadata_name,
        escape_csharp_string(&schema_type.source_name),
        schema_type.metadata_name,
        escape_csharp_string(&schema_type.source_name),
        schema_type.qualified_name,
        constructor_args,
    ));
}

fn render_polymorphic_reader(output: &mut String, schema_type: &crate::model::CsharpType) {
    let arms = render_polymorphic_arms(schema_type);
    output.push_str(&format!(
        "    private static {} Read{}(CfdValueNode node, CfdLoadContext context)\n    {{\n        if (node is not CfdObjectValue objectValue || objectValue.DeclaredType is null)\n            throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-VALUE-TYPE\", \"expected a concrete polymorphic object\", string.Empty, node.Span) }});\n        return objectValue.DeclaredType switch\n        {{\n{}\n            _ => throw new CfdLoadException(new[] {{ new CfdDiagnostic(\"CFD-REF-UNKNOWN-TYPE\", $\"unknown concrete type `{{objectValue.DeclaredType}}` for `{}`\", string.Empty, node.Span) }}),\n        }};\n    }}\n\n",
        schema_type.qualified_name,
        schema_type.metadata_name,
        arms,
        schema_type.source_name
    ));
}

fn render_polymorphic_arms(schema_type: &crate::model::CsharpType) -> String {
    schema_type
        .loader_variants
        .iter()
        .map(|variant| {
            format!(
                "            \"{}\" => Read{}(node, context),",
                escape_csharp_string(&variant.source_name),
                variant.type_name
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_annotations(annotations: &[CsharpAnnotation]) -> String {
    if annotations.is_empty() {
        return "Array.Empty<CoflowAnnotation>()".to_string();
    }
    let values = annotations
        .iter()
        .map(|annotation| {
            let arguments = annotation
                .arguments
                .iter()
                .map(|argument| format!(
                    "new CoflowAnnotationArgument(CoflowAnnotationArgumentKind.{}, {})",
                    argument.kind,
                    argument.value_expression
                ))
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "new CoflowAnnotation(\"{}\", new CoflowAnnotationArgument[] {{ {} }})",
                escape_csharp_string(&annotation.name),
                arguments
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("new CoflowAnnotation[] {{ {values} }}")
}

pub(crate) fn escape_csharp_string(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\r', "\\r")
        .replace('\n', "\\n")
        .replace('\t', "\\t")
}

fn templates() -> Result<Tera, CsharpCodegenError> {
    let mut tera = Tera::default();
    for (name, contents) in [
        ("enum.cs.tera", ENUM_TEMPLATE),
        ("type.cs.tera", TYPE_TEMPLATE),
        ("localized.cs.tera", LOCALIZED_TEMPLATE),
    ] {
        tera.add_raw_template(name, contents).map_err(|err| {
            CsharpCodegenError::new(format!("failed to add C# template `{name}`: {err}"))
        })?;
    }
    Ok(tera)
}

fn render(tera: &Tera, name: &str, context: &Context) -> Result<String, CsharpCodegenError> {
    tera.render(name, context)
        .map_err(|err| CsharpCodegenError::new(format!("failed to render `{name}`: {err}")))
}
