[package]
name = "coflow-codegen-csharp"
version = "0.9.1"
edition = "2021"
description = "C# source generator for direct CFD loading."
license = "Apache-2.0"
repository = "https://github.com/Puring103/coflow"
keywords = ["config", "game-data", "codegen", "csharp"]
categories = ["config", "game-development"]
publish = false

[lints]
workspace = true

[dependencies]
coflow-language = { path = "../coflow-language" }
coflow-codegen = { path = "../coflow-codegen" }
coflow-model = { path = "../coflow-model" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tera = "1"
unicode-ident = "1"
