// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchWriteFieldEditOutcome } from "./BatchWriteFieldEditOutcome";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type BatchWriteFieldOutcome = { revision: number, edits: Array<BatchWriteFieldEditOutcome>, diagnostics: Array<FlatDiagnostic>, affected_files: Array<string>, };
