// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved enum value.
 *
 * `variant` holds the variant identifier when the value matches a defined
 * variant. For `@flag` enums, runtime bitwise operations (`flags | other`,
 * `~flags`) can produce composite integer values that don't correspond to a
 * single declared variant; in that case `variant` is `None` and the value is
 * identified by `enum_name + value` only. Codegen and JSON serialization
 * should therefore prefer `value` (always meaningful) and treat `variant` as
 * a presentation hint that may be missing.
 */
export type CfdEnumValue = { enum_name: string, variant: string | null, value: bigint, };
