// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CfdPathSegment = { "kind": "field", "value": string } | { "kind": "index", "value": number } | { "kind": "dict_key", "value": string };
