// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateRecordFieldDraft } from "./CreateRecordFieldDraft";

export type CreateRecordDraft = { actual_type: string, fields: Array<CreateRecordFieldDraft>, };
