// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeletedRecordSnapshot } from "./DeletedRecordSnapshot";
import type { EditorChangeSet } from "./EditorChangeSet";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type DeleteRecordOutcome = { changes: EditorChangeSet, revision: number, diagnostics: Array<FlatDiagnostic>, affected_files: Array<string>,
/**
 * Authoritative snapshot of the deleted record so the front-end's undo
 * can re-insert it. `None` only when the record was missing before
 * deletion (defensive — should not happen in normal flows).
 */
deleted_snapshot: DeletedRecordSnapshot | null, };
