// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";
import type { TextRange } from "./TextRange";

export type DiagnosticTarget = { "kind": "table_field", file_path: string, coordinate: RecordCoordinate, field_path: string, } | { "kind": "record", file_path: string, coordinate: RecordCoordinate, } | { "kind": "source", file_path: string, range: TextRange | null, } | { "kind": "project_source", file_path: string, range: TextRange | null, } | { "kind": "none" };
