// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticContext = { kind: string, name: string | null, expression: string | null, quantifier: string | null, binding: string | null, item: string | null, dimension: string | null, variant: string | null, };
