// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimensionValueOrigin } from "./DimensionValueOrigin";
import type { DimensionValueState } from "./DimensionValueState";

export type DimensionValueView = { state: DimensionValueState, origin: DimensionValueOrigin | null, };
