// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimensionFileRow } from "./DimensionFileRow";

export type DimensionFileRecords = { revision: number, file_path: string, dimension: string, display_name: string, variants: Array<string>, rows: Array<DimensionFileRow>, };
