// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdValue } from "./CfdValue";

export type DimensionValueState = { "kind": "missing" } | { "kind": "value", "value": CfdValue };
