// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdPathSegment } from "./CfdPathSegment";

export type DimensionValueCoordinate = { actual_type: string, record_key: string, field: string, dimension: string, variant: string, path: Array<CfdPathSegment>, };
