// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileRecordsPatch } from "./FileRecordsPatch";

/**
 * 与一次提交绑定的文件增量；order 是权威顺序，records 只携带变化的行。
 */
export type EditorChangeSet = { base_revision: number, revision: number, files: Array<FileRecordsPatch>, };
