// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";
import type { WorkspaceViewKind } from "./WorkspaceViewKind";

export type EditorWorkspaceTab = { file_path: string, type_name: string, view_id: string, view_kind: WorkspaceViewKind, coordinate: RecordCoordinate | null, };
