// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 维度导航目标是业务文件中的类型/字段，不对应独立 CFD 文件。
 */
export type EditorDimensionTarget = { dimension: string, ownerFile: string, typeName: string, field: string | null, singleton: boolean, };
