// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable enum variant identity plus schema-provided presentation metadata.
 */
export type EnumVariantOption = { name: string, value: bigint, label: string | null, description: string | null, };
