// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordColumn } from "./RecordColumn";
import type { RecordRow } from "./RecordRow";
import type { WriterCapabilities } from "./WriterCapabilities";

export type FileRecords = { revision: number, file_path: string, type_names: Array<string>, columns: Array<RecordColumn>, records: Array<RecordRow>, capabilities: WriterCapabilities, };
