// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTypeOption = { name: string, display_name: string, record_count: number, is_singleton: boolean,
/**
 * 该实际类型在各维度下可编辑的字段，已包含继承字段。
 */
dimension_fields: { [key in string]?: Array<string> }, };
