// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileRecords } from "./FileRecords";
import type { RecordCoordinate } from "./RecordCoordinate";

export type FileRecordsPatch = { data: FileRecords, order: Array<RecordCoordinate>, };
