// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendPluginBundle } from "./FrontendPluginBundle";
import type { ProjectPluginDefaults } from "./ProjectPluginDefaults";

export type FrontendPluginProjectState = { plugins: Array<FrontendPluginBundle>, defaults: ProjectPluginDefaults, errors: Array<string>, };
