// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendPluginBundle } from "./FrontendPluginBundle";

export type FrontendPluginState = { plugins: Array<FrontendPluginBundle>, errors: Array<string>, };
