// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageCompletion } from "./LanguageCompletion";
import type { LanguageDiagnostic } from "./LanguageDiagnostic";
import type { LanguageRange } from "./LanguageRange";

export type FunctionDocumentState = { source: string, signature: string, body: string, body_range: LanguageRange, diagnostics: Array<LanguageDiagnostic>, semantic_token_data: Array<number>, semantic_token_types: Array<string>, completions: Array<LanguageCompletion>, };
