// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageTextEdit } from "./LanguageTextEdit";

export type LanguageFormattingResult = { text: string, edits: Array<LanguageTextEdit>, };
