// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageDiagnostic } from "./LanguageDiagnostic";

export type LanguageDocumentState = { diagnostics: Array<LanguageDiagnostic>, semantic_token_data: Array<number>, semantic_token_types: Array<string>, syntax_valid: boolean, };
