// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageRange } from "./LanguageRange";

export type LanguageTextEdit = { range: LanguageRange, new_text: string, };
