// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSchemaField } from "./PluginSchemaField";

/**
 * 提供给编辑器插件的只读 Schema 投影。
 */
export type PluginSchemaType = { name: string, fields: Array<PluginSchemaField>, is_singleton: boolean, record_count: number, };
