// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 插件 Schema 投影中的字段信息。
 */
export type PluginSchemaField = { name: string, type_label: string, };
