// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordCoordinate } from "./RecordCoordinate";

export type ProjectSearchHit = { file_path: string, coordinate: RecordCoordinate, field_path: string | null, preview: string | null, };
