// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type ProjectReloadedEvent = { session_id: number, changed_paths: Array<string>, revision: number, diagnostics: Array<FlatDiagnostic>, };
