// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSearchHit } from "./ProjectSearchHit";

export type ProjectSearchResults = { revision: number, hits: Array<ProjectSearchHit>, truncated: boolean, };
