// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CfdValue } from "./CfdValue";
import type { ProjectDiffChange } from "./ProjectDiffChange";

export type ProjectFieldDiff = { path: string, change: ProjectDiffChange, before?: CfdValue, after?: CfdValue, };
