// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDiffChange } from "./ProjectDiffChange";
import type { ProjectFieldDiff } from "./ProjectFieldDiff";
import type { ProjectRecordSnapshot } from "./ProjectRecordSnapshot";
import type { RecordCoordinate } from "./RecordCoordinate";

export type ProjectRecordDiff = { coordinate: RecordCoordinate, change: ProjectDiffChange, before?: ProjectRecordSnapshot, after?: ProjectRecordSnapshot, fields: Array<ProjectFieldDiff>, };
