// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A top-level field column available in a file/type table.
 */
export type RecordColumn = { name: string, type_names: Array<string>, max_summary_len: number, };
