// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChangeSet } from "./EditorChangeSet";
import type { FlatDiagnostic } from "./FlatDiagnostic";
import type { RecordCoordinate } from "./RecordCoordinate";

export type RenameRecordOutcome = { changes: EditorChangeSet, revision: number, diagnostics: Array<FlatDiagnostic>, renamed: RecordCoordinate, affected_files: Array<string>, };
