// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChangeSet } from "./EditorChangeSet";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type ReorderRecordsOutcome = { changes: EditorChangeSet, revision: number, diagnostics: Array<FlatDiagnostic>, affected_files: Array<string>, old_index: number | null, new_index: number | null, };
