// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of a custom view. Record view is implicit and cannot be created,
 * so it is not part of this enum.
 */
export type ViewKind = "table" | "graph";
