// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editing capabilities exposed to the front-end so the UI can grey out
 * disabled actions.
 */
export type WriterCapabilities = { can_edit_field: boolean, can_edit_key: boolean, can_insert_record: boolean, can_delete_record: boolean, can_reorder_records: boolean, requires_full_refresh_after_write: boolean, };
