// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimensionValueCoordinate } from "./DimensionValueCoordinate";
import type { DimensionValueState } from "./DimensionValueState";
import type { FlatDiagnostic } from "./FlatDiagnostic";

export type WriteDimensionValueOutcome = { revision: number, coordinate: DimensionValueCoordinate, old_value: DimensionValueState, new_value: DimensionValueState, diagnostics: Array<FlatDiagnostic>, affected_files: Array<string>, };
