<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <RootNamespace>CoflowRuntime</RootNamespace>
    <AssemblyName>Coflow.Cfd.Runtime</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Coflow.Cfd.Runtime</PackageId>
    <Description>Strongly typed CFD loading, compilation, function binding, reload, and virtual machine runtime.</Description>
    <PackageVersion>0.9.1</PackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Unity/link.xml"
          Pack="true"
          PackagePath="contentFiles/any/any/Coflow.Cfd.Runtime/link.xml" />
  </ItemGroup>
</Project>
