[package]
name = "coflow-language"
version = "0.9.1"
edition = "2021"
description = "Coflow's unified CFT and CFD language facade."
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
coflow-cft = { path = "../coflow-cft" }
coflow-cfd = { path = "../coflow-cfd" }
coflow-structure = { path = "../coflow-structure" }
