[package]
name = "coflow-lsp"
version = "0.9.1"
edition = "2021"
description = "Language Server Protocol implementation for Coflow."
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
coflow-format = { path = "../coflow-format" }
coflow-language = { path = "../coflow-language" }
coflow-runtime = { path = "../coflow-runtime" }
serde_json = { version = "1", features = ["preserve_order"] }
similar = "2"
