//! Lua 5.1 code generator and JSON loader generator.

#![cfg_attr(
    not(test),
    deny(
        clippy::dbg_macro,
        clippy::expect_used,
        clippy::panic,
        clippy::panic_in_result_fn,
        clippy::todo,
        clippy::unimplemented,
        clippy::unreachable,
        clippy::unwrap_used
    )
)]

use coflow_api::{
    ArtifactFile, ArtifactSet, CodeGenerator, CodegenContext, CodegenDescriptor,
    DecodedOutputOptions, Diagnostic, DiagnosticSet, LoaderDescriptor, LoaderGenerationContext,
    LoaderGenerator, ProviderBundle, ProviderRegistrationError,
};
use coflow_cft::CftValueType;
use coflow_codegen_core::CodegenModel;
use std::fmt::Write;

const LUA_SAFE_INTEGER: i64 = 9_007_199_254_740_991;

pub const LUA_CODEGEN_DESCRIPTOR: CodegenDescriptor = CodegenDescriptor {
    id: "lua",
    display_name: "Lua 5.1",
    language: "lua",
    file_extensions: &["lua"],
    needs_model_for_build: true,
};

pub const LUA_JSON_LOADER_DESCRIPTOR: LoaderDescriptor = LoaderDescriptor {
    id: "lua-json",
    code: "lua",
    data: "json",
};

#[derive(Debug, Default, Clone, Copy)]
pub struct LuaCodeGenerator;

#[derive(Debug, Default, Clone, Copy)]
pub struct LuaJsonLoaderGenerator;

#[derive(Debug)]
struct EmptyOptions;

/// Declares Lua codegen and compatible loader roles.
///
/// # Errors
///
/// Returns an error when a role id conflicts within the bundle.
pub fn provider_bundle() -> Result<ProviderBundle, ProviderRegistrationError> {
    let mut bundle = ProviderBundle::default();
    bundle.add_codegen(LuaCodeGenerator)?;
    bundle.add_loader(LuaJsonLoaderGenerator)?;
    Ok(bundle)
}

impl CodeGenerator for LuaCodeGenerator {
    fn descriptor(&self) -> &'static CodegenDescriptor {
        &LUA_CODEGEN_DESCRIPTOR
    }

    fn decode_options(
        &self,
        options: &serde_json::Value,
    ) -> Result<DecodedOutputOptions, DiagnosticSet> {
        decode_empty_options("lua", options)
    }

    fn generate(
        &self,
        ctx: CodegenContext<'_>,
        options: &DecodedOutputOptions,
    ) -> Result<ArtifactSet, DiagnosticSet> {
        options.require::<EmptyOptions>("lua")?;
        let model = CodegenModel::build(ctx.schema, ctx.model, ctx.id_as_enum_variants)?;
        validate_safe_enums(&model)?;
        artifacts(vec![ArtifactFile::text(
            "coflow_types.lua",
            render_types(&model),
        )])
    }
}

impl LoaderGenerator for LuaJsonLoaderGenerator {
    fn descriptor(&self) -> &'static LoaderDescriptor {
        &LUA_JSON_LOADER_DESCRIPTOR
    }

    fn decode_options(
        &self,
        options: &serde_json::Value,
    ) -> Result<DecodedOutputOptions, DiagnosticSet> {
        decode_empty_options("lua-json", options)
    }

    fn generate(
        &self,
        ctx: LoaderGenerationContext<'_>,
        options: &DecodedOutputOptions,
    ) -> Result<ArtifactSet, DiagnosticSet> {
        options.require::<EmptyOptions>("lua-json")?;
        let model = CodegenModel::build(ctx.schema, ctx.model, ctx.id_as_enum_variants)?;
        validate_safe_enums(&model)?;
        artifacts(vec![ArtifactFile::text(
            "coflow_json.lua",
            render_json_loader(&model),
        )])
    }
}

fn decode_empty_options(
    id: &'static str,
    options: &serde_json::Value,
) -> Result<DecodedOutputOptions, DiagnosticSet> {
    if options.as_object().is_some_and(serde_json::Map::is_empty) {
        Ok(DecodedOutputOptions::new(id, EmptyOptions))
    } else {
        Err(DiagnosticSet::one(Diagnostic::error(
            "LUA-OPTIONS",
            "CODEGEN",
            format!("{id} does not accept options"),
        )))
    }
}

fn validate_safe_enums(model: &CodegenModel) -> Result<(), DiagnosticSet> {
    let mut diagnostics = DiagnosticSet::empty();
    for item in &model.enums {
        for variant in &item.variants {
            if variant.value.unsigned_abs() > LUA_SAFE_INTEGER as u64 {
                diagnostics.push(Diagnostic::error(
                    "LUA-INTEGER-RANGE",
                    "CODEGEN",
                    format!(
                        "enum variant `{}.{}` value {} is not exactly representable by Lua 5.1",
                        item.name, variant.name, variant.value
                    ),
                ));
            }
        }
    }
    if diagnostics.is_empty() {
        Ok(())
    } else {
        Err(diagnostics)
    }
}

fn artifacts(files: Vec<ArtifactFile>) -> Result<ArtifactSet, DiagnosticSet> {
    ArtifactSet::new(files).map_err(|error| {
        DiagnosticSet::one(Diagnostic::error(
            "LUA-ARTIFACT",
            "ARTIFACT",
            error.to_string(),
        ))
    })
}

fn render_types(model: &CodegenModel) -> String {
    let mut out = String::from(
        "-- Generated by Coflow. Lua 5.1 compatible. Do not edit.\nlocal M = {}\n\nM.NULL = {}\nM.enums = {}\nM.types = {}\nM.tables = {}\nM.singletons = {}\n\n",
    );
    for item in &model.enums {
        let _ = writeln!(out, "M.enums[{:?}] = {{", item.name);
        for variant in &item.variants {
            let _ = writeln!(out, "  [{:?}] = {},", variant.name, variant.value);
            let _ = writeln!(
                out,
                "  [{:?}] = {},",
                format!("{}.{}", item.name, variant.name),
                variant.value
            );
        }
        out.push_str("}\n");
    }
    out.push('\n');
    for ty in &model.types {
        let _ = writeln!(out, "---@class {}", pascal(&ty.name));
        if !ty.is_abstract {
            out.push_str("---@field id string\n");
        }
        for field in &ty.all_fields {
            let _ = writeln!(
                out,
                "---@field {} {}",
                field.name,
                lua_annotation(&field.value_type, model)
            );
        }
        let _ = writeln!(out, "local {} = {{}}", pascal(&ty.name));
        let _ = writeln!(out, "{}.__index = {}", pascal(&ty.name), pascal(&ty.name));
        let _ = writeln!(out, "M[{:?}] = {}", pascal(&ty.name), pascal(&ty.name));
        let _ = writeln!(
            out,
            "M.types[{:?}] = {{ class = {}, fields = {{",
            ty.name,
            pascal(&ty.name)
        );
        for field in &ty.all_fields {
            let _ = writeln!(
                out,
                "  {{ name = {:?}, descriptor = {} }},",
                field.name,
                lua_descriptor(&field.value_type, model, field.is_localized)
            );
        }
        out.push_str("} }\n\n");
    }
    for table in &model.table_names {
        let _ = writeln!(out, "M.tables[{:?}] = true", table);
    }
    for singleton in &model.singleton_names {
        let _ = writeln!(out, "M.singletons[{:?}] = true", singleton);
    }
    out.push_str("\nreturn M\n");
    out
}

fn render_json_loader(_model: &CodegenModel) -> String {
    String::from(
        r#"-- Generated by Coflow. Lua 5.1 compatible. Do not edit.
local json = require("cjson.safe")
local schema = require("coflow_types")
local M = {}

local SAFE_INTEGER = 9007199254740991

local function read_file(path)
  local file = io.open(path, "rb")
  if not file then return {} end
  local text = file:read("*a")
  file:close()
  local value, err = json.decode(text)
  if value == nil then return nil, "failed to decode " .. path .. ": " .. tostring(err) end
  return value
end

local function parse_enum(name, value)
  if type(value) == "number" and value % 1 == 0 and math.abs(value) <= SAFE_INTEGER then return value end
  if type(value) ~= "string" then return nil, "expected symbolic enum string" end
  local enum = schema.enums[name]
  local known = enum and enum[value]
  if known ~= nil then return known end
  local prefix = name .. "("
  if string.sub(value, 1, string.len(prefix)) == prefix and string.sub(value, -1) == ")" then
    local numeric = tonumber(string.sub(value, string.len(prefix) + 1, -2))
    if numeric and math.abs(numeric) <= SAFE_INTEGER then return numeric end
  end
  return nil, "invalid " .. name .. " value " .. value
end

local hydrate
hydrate = function(value, descriptor, database)
  if descriptor.localized then
    local inner, err = hydrate(value, descriptor.value, database)
    if err then return nil, err end
    return { default = inner }
  end
  local kind = descriptor.kind
  if kind == "int" then
    if type(value) ~= "number" or value % 1 ~= 0 or math.abs(value) > SAFE_INTEGER then
      return nil, "integer is outside the Lua 5.1 exact range"
    end
    return value
  elseif kind == "float" or kind == "bool" or kind == "string" then
    return value
  elseif kind == "enum" then
    return parse_enum(descriptor.name, value)
  elseif kind == "ref" then
    return { _coflow_ref = descriptor.name, id = value }
  elseif kind == "nullable" then
    if value == nil or value == json.null then return nil end
    return hydrate(value, descriptor.value, database)
  elseif kind == "array" then
    local result = {}
    for index, item in ipairs(value) do
      local converted, err = hydrate(item, descriptor.value, database)
      if err then return nil, err end
      result[index] = converted == nil and schema.NULL or converted
    end
    return result
  elseif kind == "dict" then
    local result = {}
    for key, item in pairs(value) do
      local converted, err = hydrate(item, descriptor.value, database)
      if err then return nil, err end
      result[key] = converted
    end
    return result
  elseif kind == "object" then
    return M.hydrate_record(value, value["$type"] or descriptor.name, database)
  end
  return nil, "unknown Coflow descriptor kind " .. tostring(kind)
end

function M.hydrate_record(raw, type_name, database)
  local metadata = schema.types[type_name]
  if not metadata then return nil, "unknown Coflow type " .. tostring(type_name) end
  local record = setmetatable({}, metadata.class)
  record._coflow_type = type_name
  record.id = raw.id
  for _, field in ipairs(metadata.fields) do
    local converted, err = hydrate(raw[field.name], field.descriptor, database)
    if err then return nil, type_name .. "." .. field.name .. ": " .. err end
    record[field.name] = converted
  end
  return record
end

local resolve
resolve = function(value, descriptor, database)
  if value == nil or value == schema.NULL then return value end
  if descriptor.localized then
    value.default = resolve(value.default, descriptor.value, database)
    return value
  end
  local kind = descriptor.kind
  if kind == "ref" then
    local records = database[value._coflow_ref]
    return records and records[value.id] or nil
  elseif kind == "nullable" then
    return resolve(value, descriptor.value, database)
  elseif kind == "array" then
    for index, item in ipairs(value) do value[index] = resolve(item, descriptor.value, database) end
  elseif kind == "dict" then
    for key, item in pairs(value) do value[key] = resolve(item, descriptor.value, database) end
  elseif kind == "object" then
    local metadata = schema.types[value._coflow_type]
    if metadata then
      for _, field in ipairs(metadata.fields) do
        value[field.name] = resolve(value[field.name], field.descriptor, database)
      end
    end
  end
  return value
end

function M.load(directory)
  local database = {}
  local raw_tables = {}
  for type_name in pairs(schema.tables) do
    local rows, err = read_file(directory .. "/" .. type_name .. ".json")
    if not rows then return nil, err end
    raw_tables[type_name] = rows
    database[type_name] = {}
    for _, row in ipairs(rows) do database[type_name][row.id] = row end
  end
  for type_name, rows in pairs(raw_tables) do
    local hydrated = {}
    for _, row in ipairs(rows) do
      local record, err = M.hydrate_record(row, row["$type"] or type_name, database)
      if not record then return nil, err end
      hydrated[record.id] = record
    end
    database[type_name] = hydrated
  end
  for type_name in pairs(schema.singletons) do
    local rows, err = read_file(directory .. "/" .. type_name .. ".json")
    if not rows then return nil, err end
    if rows[1] then
      local record, hydrate_err = M.hydrate_record(rows[1], rows[1]["$type"] or type_name, database)
      if not record then return nil, hydrate_err end
      database[type_name] = record
    end
  end
  for type_name, records in pairs(database) do
    if schema.tables[type_name] then
      for _, record in pairs(records) do
        local metadata = schema.types[record._coflow_type]
        for _, field in ipairs(metadata.fields) do record[field.name] = resolve(record[field.name], field.descriptor, database) end
      end
    elseif schema.singletons[type_name] and records then
      local metadata = schema.types[records._coflow_type]
      for _, field in ipairs(metadata.fields) do records[field.name] = resolve(records[field.name], field.descriptor, database) end
    end
  end
  return database
end

return M
"#,
    )
}

fn lua_annotation(value: &CftValueType, model: &CodegenModel) -> String {
    match value {
        CftValueType::Int | CftValueType::Float => "number".to_string(),
        CftValueType::Bool => "boolean".to_string(),
        CftValueType::String => "string".to_string(),
        CftValueType::Enum(_) => "number".to_string(),
        CftValueType::RecordRef(name) | CftValueType::Object(name) => pascal(name),
        CftValueType::Array(inner) => format!("{}[]", lua_annotation(inner, model)),
        CftValueType::Dict(_, value) => format!("table<any, {}>", lua_annotation(value, model)),
        CftValueType::Nullable(inner) => format!("{}|nil", lua_annotation(inner, model)),
    }
}

fn lua_descriptor(value: &CftValueType, model: &CodegenModel, localized: bool) -> String {
    let descriptor = match value {
        CftValueType::Int => "{ kind = \"int\" }".to_string(),
        CftValueType::Float => "{ kind = \"float\" }".to_string(),
        CftValueType::Bool => "{ kind = \"bool\" }".to_string(),
        CftValueType::String => "{ kind = \"string\" }".to_string(),
        CftValueType::Enum(name) => format!("{{ kind = \"enum\", name = {name:?} }}"),
        CftValueType::RecordRef(name) => format!("{{ kind = \"ref\", name = {name:?} }}"),
        CftValueType::Object(name) => {
            let polymorphic = model
                .type_by_name(name)
                .is_some_and(|ty| ty.concrete_types.len() > 1);
            format!("{{ kind = \"object\", name = {name:?}, polymorphic = {polymorphic} }}")
        }
        CftValueType::Array(inner) => format!(
            "{{ kind = \"array\", value = {} }}",
            lua_descriptor(inner, model, false)
        ),
        CftValueType::Dict(_, inner) => format!(
            "{{ kind = \"dict\", value = {} }}",
            lua_descriptor(inner, model, false)
        ),
        CftValueType::Nullable(inner) => format!(
            "{{ kind = \"nullable\", value = {} }}",
            lua_descriptor(inner, model, false)
        ),
    };
    if localized {
        format!("{{ localized = true, value = {descriptor} }}")
    } else {
        descriptor
    }
}

fn pascal(value: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for character in value.chars() {
        if matches!(character, '_' | '-' | ' ') {
            upper = true;
        } else if upper {
            out.extend(character.to_uppercase());
            upper = false;
        } else {
            out.push(character);
        }
    }
    out
}
