//! Generates C# constant classes for tables annotated with `@KeyAsEnumValue`.
//!
//! This is a build-time augmentation: the schema declares `@KeyAsEnumValue`
//! on a `type` whose `@id` is a `string`, and the build pipeline scans the
//! loaded data model for that table to emit a `<Type>Id.cs` file with a
//! `public static class <Type>Id` listing every record's id.
//!
//! The runtime field type stays `string`; this is purely a developer-facing
//! convenience so callsites can write `GeneId.SimpleDivision` instead of the
//! raw string literal.

use coflow_cft::CftContainer;
use coflow_data_model::{CfdDataModel, CfdIdValue};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

pub fn write_key_as_enum_value_files(
    schema: &CftContainer,
    model: &CfdDataModel,
    namespace: &str,
    dir: &Path,
) -> Result<(), String> {
    for schema_type in schema.all_types() {
        if !schema_type
            .annotations
            .iter()
            .any(|annotation| annotation.name == "KeyAsEnumValue")
        {
            continue;
        }

        // The id field must exist (validated by the schema compiler) and must
        // be a string for the generated constants to make sense; otherwise
        // skip with no output.
        let Some(id_field) = schema_type
            .all_fields
            .iter()
            .find(|field| field.annotations.iter().any(|a| a.name == "id"))
        else {
            continue;
        };
        if id_field.ty != "string" {
            continue;
        }

        let mut entries: Vec<String> = Vec::new();
        for (_record_id, record) in model.records_of_type(&schema_type.name) {
            if let Some(value) = record.fields.get(&id_field.name) {
                if let Some(id) = id_value_string(value) {
                    entries.push(id);
                }
            }
        }
        entries.sort();
        entries.dedup();

        let class_name = format!("{}Id", schema_type.name);
        let mut text = String::new();
        text.push_str("// <auto-generated />\n");
        text.push_str("#nullable enable\n\n");
        let _ = writeln!(text, "namespace {namespace};\n");
        let _ = writeln!(text, "public static class {class_name}");
        text.push_str("{\n");
        for id in &entries {
            let ident = sanitize_identifier(id);
            let literal = csharp_string_literal(id);
            let _ = writeln!(text, "    public const string {ident} = {literal};");
        }
        text.push_str("}\n");

        fs::create_dir_all(dir)
            .map_err(|err| format!("failed to create output dir `{}`: {err}", dir.display()))?;
        let path = dir.join(format!("{class_name}.cs"));
        fs::write(&path, text)
            .map_err(|err| format!("failed to write `{}`: {err}", path.display()))?;
    }
    Ok(())
}

fn id_value_string(value: &coflow_data_model::CfdValue) -> Option<String> {
    match value {
        coflow_data_model::CfdValue::String(value) => Some(value.clone()),
        _ => None,
    }
}

#[allow(dead_code)]
fn id_value_to_string(id: &CfdIdValue) -> Option<String> {
    match id {
        CfdIdValue::String(value) => Some(value.clone()),
        _ => None,
    }
}

fn csharp_string_literal(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            ch => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn sanitize_identifier(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 1);
    for (index, ch) in value.chars().enumerate() {
        let allowed = ch == '_' || ch.is_ascii_alphanumeric();
        if index == 0 && (ch.is_ascii_digit() || !allowed) {
            out.push('_');
        }
        if allowed {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}
