<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Coflow.Cfd.Runtime">
      <HintPath>../Coflow.Cfd.Runtime/bin/$(Configuration)/netstandard2.1/Coflow.Cfd.Runtime.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
