[package]
name = "coflow"
version.workspace = true
edition = "2021"
description = "Project-level command-line tools for Coflow."
license = "Apache-2.0"
repository = "https://github.com/Puring103/coflow"
publish = false

[lints]
workspace = true

[dependencies]
atomicwrites = "0.4.4"
clap = { version = "4", features = ["derive"] }
coflow-format = { path = "../crates/coflow-format" }
coflow-lsp = { path = "../crates/coflow-lsp" }
coflow-project = { path = "../crates/coflow-project" }
dirs = "6"
include_dir = "0.7"
self_update = { version = "0.42", default-features = false, features = ["archive-tar", "compression-flate2", "rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

[dev-dependencies]
tempfile = "3"
