// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticItem = { severity: string, code: string, stage: string, message: string, file_path: string | null, record_key: string | null, field_path: string | null, };
