// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DictKey = { "kind": "Str", v: string, } | { "kind": "Int", v: bigint, } | { "kind": "Enum", enum_name: string, variant: string, int_value: bigint, };
