// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldValue } from "./FieldValue";

export type FieldCell = { name: string, value: FieldValue, };
