// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldPathSegment = { "kind": "Field", name: string, } | { "kind": "Index", i: number, };
