// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DictEntry } from "./DictEntry";
import type { FieldCell } from "./FieldCell";

export type FieldValue = { "kind": "Null" } | { "kind": "Bool", v: boolean, } | { "kind": "Int", v: bigint, } | { "kind": "Float", v: number, } | { "kind": "Str", v: string, } | { "kind": "Enum", enum_name: string, variant: string, int_value: bigint, } | { "kind": "Object", actual_type: string, fields: Array<FieldCell>, } | { "kind": "Ref", target_type: string, target_key: string, target_file: string | null, } | { "kind": "Array", items: Array<FieldValue>, } | { "kind": "Dict", entries: Array<DictEntry>, };
