// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Schema information for a single field on a type.
 * Used to enable schema-aware editing (e.g. creating a nullable Object value).
 */
export type FieldSchema = { name: string, 
/**
 * Human-readable type string (e.g. "Stats", "Stats?", "int[]")
 */
type_str: string, 
/**
 * If this field's type is `T?` where T is an Object type, this is T.
 * Used by the UI to offer a "Create T object" button for null values.
 */
nullable_object_type: string | null, 
/**
 * If this field's type is `[T?]` (Array of nullable Object T), this is T.
 * Used by the UI to offer a "＋ T" button when adding items to an empty array.
 */
array_nullable_element_type: string | null, 
/**
 * Whether this field has a default value (implies it's optional in practice).
 */
has_default: boolean, 
/**
 * Human-readable default value string (e.g. "0", "false", "null", "[]").
 * None if the field has no default.
 */
default_str: string | null, };
