// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTreeNode = { name: string, path: string, is_dir: boolean, in_sources: boolean, children: Array<FileTreeNode>, 
/**
 * Number of records in this file (0 for directories).
 */
record_count: number, };
