// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldCell } from "./FieldCell";

export type GraphNode = { id: string, key: string, actual_type: string, file_path: string, in_focus_file: boolean, is_collapsed: boolean, fields: Array<FieldCell>, };
