// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A record that holds a reference pointing to another record.
 */
export type IncomingRef = { 
/**
 * The record key that holds the reference.
 */
source_key: string, 
/**
 * The type of the record that holds the reference.
 */
source_type: string, 
/**
 * File where the source record lives.
 */
source_file: string, 
/**
 * Field path within the source record where the Ref appears (e.g. "weapon" or "rewards[0]").
 */
field_path: string, };
