// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticItem } from "./DiagnosticItem";
import type { FileTreeNode } from "./FileTreeNode";

export type ProjectSnapshot = { session_id: number, file_tree: Array<FileTreeNode>, diagnostics: Array<DiagnosticItem>, };
