// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldCell } from "./FieldCell";
import type { SpreadSource } from "./SpreadSource";

export type RecordRow = { key: string, actual_type: string, fields: Array<FieldCell>, 
/**
 * Field names that come from spread entries (not directly editable).
 */
spread_fields: Array<string>, 
/**
 * Records spread into this record (e.g. `...&base_item` → [{key:"base_item", file:"..."}]).
 */
spread_sources: Array<SpreadSource>, };
