// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldCell } from "./FieldCell";

export type RecordRow = { key: string, actual_type: string, fields: Array<FieldCell>, 
/**
 * Field names that come from spread entries (not directly editable).
 */
spread_fields: Array<string>, };
