// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight summary of a record for the command palette / jump-to-record.
 */
export type RecordBrief = { key: string, actual_type: string, file_path: string, };
