// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldCell } from "./FieldCell";
import type { SpreadSource } from "./SpreadSource";

export type RecordRow = { key: string, actual_type: string, 
/**
 * File path (relative to project root) where this record lives.
 * Populated for all rows; useful when aggregating across files.
 */
file_path: string, fields: Array<FieldCell>, 
/**
 * Field names that come from spread entries (not directly editable).
 */
spread_fields: Array<string>, 
/**
 * Records spread into this record (e.g. `...&base_item` → [{key:"base_item", file:"..."}]).
 */
spread_sources: Array<SpreadSource>, 
/**
 * True when this record was built from the raw AST rather than the model
 * (model build failed for this record — it may have missing required fields).
 */
is_fallback: boolean, };
