// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A record that matched a text search query.
 */
export type SearchHit = { key: string, actual_type: string, file_path: string, 
/**
 * The first field path that matched (e.g. "name" or "stats.hp")
 */
match_field: string, 
/**
 * The matched value as a short string for display
 */
match_value: string, };
