// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A record key that is spread into this record, with the file path it comes from.
 */
export type SpreadSource = { key: string, 
/**
 * File path (relative to project root) where the spread source record lives.
 * Empty string if the file could not be determined.
 */
file: string, };
